import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { expect, test } from "@playwright/test";
import { parse } from "yaml";
import { CI_WORKFLOW_REL_PATH, stepWorkingDirectory } from "../../../.claude/hooks/push-guard.mjs";
import { repoRoot } from "../preflight";

/**
 * Workflow parity (T-020 plan §4.7, rebuilt by T-045) — no browser: the
 * dormant .github/workflows/ci.yml cannot execute before the repo's first
 * GitHub push (no remote exists), so THIS spec is its machine validation.
 *
 * These are FACTS ABOUT THE ONE CI JOB: valid YAML, the pinned runner, the
 * commands and their order, the SHA pins, the apt set, the boot step. The
 * rules EVERY workflow file obeys — the GITHUB_TOKEN scope — live next
 * door in workflow-permissions.spec.ts, because they are not about ci.yml
 * (T-045 criterion 3).
 *
 * ── WHAT T-045 CHANGED ───────────────────────────────────────────────
 * The expected commands used to be a sixteen-entry array with a comment
 * saying it mirrored docs/CONVENTIONS.md "Build & test". A mirror agrees
 * with whatever it was last copied from: the workflow and the spec could
 * agree with each other while both drifted from the doc that governs them
 * — and did (the doc listed `npm run typecheck` for tools/e2e, which no
 * CI step ran). The list is now PARSED out of that section, so the doc is
 * the only place a command is written down, and the deliberate
 * divergences are an explicit, argued mapping (CI_SEQUENCE below) rather
 * than an untracked difference. Reword a command in CONVENTIONS and this
 * spec goes red naming both sides — pinned by the fixtures at the end.
 *
 * ── WHAT T-054 CHANGED ───────────────────────────────────────────────
 * 1. `supertaskr-index index --check` joins CI_SEQUENCE after the cargo
 *    suite. CI had NEVER gated graph currency: ci.yml runs bare `cargo
 *    test`, which skips `#[ignore]`d tests, and `self_graph_is_current`
 *    — the one byte-comparison against the committed graph.json — is
 *    `#[ignore]`d. A stale graph passed green, because the dogfood
 *    fixtures assert against the committed graph and a stale graph
 *    agrees with fixtures that match it. `index --watch` and `arch` are
 *    LOCAL_ONLY: a watcher runs until stopped, and `arch` reports from
 *    the committed graph rather than gating.
 * 2. Two of the four divergences CLOSED — the lint and the boot check
 *    were only CI spelling a documented command a second way, so both
 *    now invoke the documented command (the xvfb wrapper stays real).
 *    What remains are the two ENVIRONMENT differences the doc always
 *    claimed: `npm ci` for app/, and playwright's `--with-deps`.
 * 3. The derivation stopped being SILENT about structure. T-045's
 *    verifier attacked it twenty-four ways; 18 red loudly, 3 are
 *    correctly tolerated, and 3 were invisible (problems=0, steps=17) —
 *    all one shape, a command ARRIVING somewhere `commandBullets` does
 *    not look, because it splits on a newline followed by "- " at
 *    COLUMN 0. Indented bullets and fenced blocks inside "Build & test"
 *    now push a problem naming the structure (structuralProblems).
 *
 * ── WHAT T-153-s8 CHANGED ────────────────────────────────────────────
 * `npm run capabilities:check` joins CI_SEQUENCE and `npm run
 * capabilities` joins LOCAL_ONLY. docs/CAPABILITIES.md is GENERATED from
 * the test names in this directory, and until that step existed NOTHING
 * asked whether the committed file still matched a fresh generation —
 * not this job, not a CONVENTIONS command bullet, not a spec. The census
 * went stale, was regenerated by hand at a checkpoint, and went stale
 * again with no instrument in between.
 *
 * The keeper is a CI STEP and deliberately not a body in this suite: the
 * failure mode both recorded instances actually took was an integrator
 * regenerating by hand at a checkpoint, which no lane body observes,
 * while CI is the seat that sees every merge. So this file gains two
 * DATA entries and no assertion — the parity bodies that already exist
 * are what bind them, in both directions.
 *
 * ── WHAT T-237-s3 CHANGED ────────────────────────────────────────────
 * THIS FILE GAINED A SECOND READER AND DID NOT KNOW. T-237 made
 * `.claude/hooks/push-guard.mjs` READ `.github/workflows/ci.yml` at push
 * time: `gh` names the step that failed, and the guard looks that step
 * up in the workflow's own `working-directory:` keys to tell the seat
 * which package the red run was testing and whether the tree being
 * pushed reaches it. Every body above pins a step's COMMAND against
 * docs/CONVENTIONS.md and none of them looks at a step's NAME — which is
 * the key that map is keyed on — so the guard's most useful sentence
 * could degrade with this suite entirely green.
 *
 * AND THE DEGRADATION IS NOT AN ADMISSION, which is the half worth
 * writing down. `reachSentence` collapses "this step is unplaceable"
 * into "this step declares no `working-directory`": `stepWorkingDirectory`
 * answers `undefined` for both and the guard has no third value to read,
 * so a step the scanner cannot place is announced as running at the
 * REPOSITORY ROOT where EVERY push reaches it — byte-identical to what a
 * genuinely root-running step gets. A confident falsehood, not a lost
 * sentence. (The hook's own "that step's package is unknown here" is a
 * DIFFERENT branch: an unreadable workflow file, never an unreadable
 * step. T-237-s3's card predicted that sentence and the code does not
 * produce it; the repository won, and the guard-side repair is routed as
 * T-237-s7 because the hook is another card's fence.)
 *
 * The last section of this file is the keeper for that dependency, and
 * the scanner it checks is IMPORTED rather than re-implemented, for the
 * same reason the command list stopped being a sixteen-entry array.
 */

interface WorkflowStep {
  name?: string;
  uses?: string;
  run?: string;
  "working-directory"?: string;
  env?: Record<string, string>;
  with?: Record<string, unknown>;
  // T-278: a step's CONDITION is a fact about the job like its command.
  // The disk reading taken after the lane is only worth a step while it
  // runs after a RED one, and `if:` is where that is written.
  if?: string;
}

/** A workflow step's identity for parity purposes: what it runs, where. */
interface Step {
  dir: string | undefined;
  run: string;
}

const stepKey = (s: Step): string => `[${s.dir ?? "(root)"}] ${s.run}`;
const docKey = (dir: string, cmd: string): string => `[${dir}] ${cmd}`;

// ── reading docs/CONVENTIONS.md ────────────────────────────────────────

export function readConventions(): string {
  return readFileSync(path.join(repoRoot, "docs", "CONVENTIONS.md"), "utf8");
}

/**
 * The "Build & test" section, verbatim. THROWS if it is missing or empty:
 * a derivation that silently expects nothing is worse than the array it
 * replaced, so the one input everything else reads is checked first.
 */
export function buildAndTestSection(md: string): string {
  const section = md
    .split(/^## /m)
    .find((s) => s.startsWith("Build & test"))
    ?.replace(/^Build & test[^\n]*\n/, "");
  if (section === undefined || section.trim() === "") {
    throw new Error(
      'docs/CONVENTIONS.md has no non-empty "## Build & test" section — the ' +
        "workflow parity spec derives every expected command from it, so a " +
        "renamed or emptied section is a hard failure, never an empty expectation.",
    );
  }
  return section;
}

/**
 * The per-package command bullets of that section: a bullet marked
 * `run from <dir>/:` followed by `·`-separated backticked commands.
 *
 * The rule is the doc's own typography and it is deliberately strict —
 * the command list ends at the first `·` segment that does not open with
 * a backtick, so the tools/e2e bullet's trailing `Exit 0 booted · 1 the
 * boot failed · …` legend is prose, not commands, and a command that
 * loses its backticks disappears from the list (which reds this spec)
 * instead of being guessed at.
 */
export function commandBullets(section: string): { dir: string; commands: string[] }[] {
  const bullets = section
    .split(/\n(?=- )/)
    .map((b) => b.replace(/\s+/g, " ").trim())
    .filter((b) => b.startsWith("- "));
  const out: { dir: string; commands: string[] }[] = [];
  for (const bullet of bullets) {
    const marker = /run from ([A-Za-z0-9._/-]+)\/:/.exec(bullet);
    if (marker === null) continue;
    const commands: string[] = [];
    for (const segment of bullet.slice(marker.index + marker[0].length).split("·")) {
      const trimmed = segment.trim();
      if (!trimmed.startsWith("`")) break;
      const span = /^`([^`]+)`/.exec(trimmed);
      if (span === null) break;
      commands.push(span[1]!);
    }
    out.push({ dir: marker[1]!, commands });
  }
  return out;
}

/**
 * The structures `commandBullets` CANNOT see, named out loud (T-045-s4).
 *
 * The splitter is `\n(?=- )` — a newline followed by "- " at COLUMN 0 —
 * so anything INDENTED is glued to the preceding bullet's chunk and read
 * as that bullet's prose, and a fenced block is just more prose. T-045's
 * verifier measured the consequence: of twenty-four attacks on the
 * derivation, 18 red loudly and 3 are correctly tolerated, but 3 were
 * SILENT — an indented sub-bullet, an indented sub-bullet carrying its
 * own `run from <dir>/:` marker, and a fenced block after a bullet. Each
 * derived `problems=0` with the step list unchanged: the doc grew a
 * command and the lane said nothing. That asymmetry is the dangerous
 * one, because writing NEW commands into that section is exactly how
 * this mechanism is maintained — a command that ARRIVES in an unread
 * shape is the one that stays invisible.
 *
 * This teaches the parser no markdown. It flags the two SHAPES and says
 * what to do, the way a fifth `run from` bullet already does.
 *
 * The rule is the splitter's own, not markdown's: only a leading "- " is
 * a bullet here. `+` and `*` are deliberately NOT flagged — the section
 * legitimately wraps prose onto a line beginning "  + supertaskr-index crate
 * suite", and a rule that reds on real prose teaches editors to route
 * around it.
 */
export function structuralProblems(section: string): string[] {
  const problems: string[] = [];
  section.split("\n").forEach((line, i) => {
    const where = `docs/CONVENTIONS.md "Build & test" line ${i + 1} (of the section)`;
    if (/^[ \t]+- /.test(line)) {
      problems.push(
        `${where} is an INDENTED BULLET: ${JSON.stringify(line.trim().slice(0, 48))}. ` +
          'The derivation splits on a newline followed by "- " at COLUMN 0, so an ' +
          "indented bullet is glued to the preceding bullet's prose — every command " +
          "on it is INVISIBLE to CI parity, and so is a `run from <dir>/:` marker of " +
          "its own. Unindent it, or fold it into its parent bullet.",
      );
    }
    if (/^[ \t]*```/.test(line)) {
      problems.push(
        `${where} carries a CODE FENCE. The derivation reads \`·\`-separated ` +
          "backticked commands out of bullet prose and never looks inside a fence, " +
          "so commands in one are INVISIBLE to CI parity. Put them in a " +
          "`run from <dir>/:` bullet instead.",
      );
    }
  });
  return problems;
}

/**
 * The section's CI bullet — where a reader goes to learn how CI differs
 * from local. Every disposition that is not "verbatim" has to be written
 * down THERE, not merely somewhere in the doc: a divergence buried in
 * another bullet is one the next editor of ci.yml will not meet.
 */
export function ciBullet(section: string): string {
  const bullet = section
    .split(/\n(?=- )/)
    .map((b) => b.replace(/\s+/g, " ").trim())
    .find((b) => b.startsWith("- CI (.github/workflows/ci.yml)"));
  return bullet ?? "";
}

// ── the CI correspondence: the doc's commands, and how CI runs them ────

type Correspondence =
  /** CI runs this CONVENTIONS command as written, in the same directory. */
  | { kind: "verbatim"; dir: string; cmd: string }
  /** CI runs it differently. The divergence is argued here AND documented
   *  in CONVENTIONS' CI bullet — the derivation checks the second half, so
   *  a divergence cannot live in the test alone. */
  | { kind: "mapped"; dir: string; cmd: string; steps: Step[]; why: string }
  /** A step CI adds that no per-package bullet lists, documented elsewhere
   *  in the same section. */
  | { kind: "ci-only"; step: Step; why: string };

/**
 * Every expected run step, in the order ci.yml runs them (plan §7: token
 * lint → parser → app → cargo test → cargo audit → e2e → xvfb boot).
 * ORDER is a fact about the one CI job, so it lives here; the command
 * STRINGS are read out of CONVENTIONS.
 */
const CI_SEQUENCE: Correspondence[] = [
  {
    kind: "mapped",
    dir: "tools/e2e",
    cmd: "npm run lint:tokens",
    steps: [
      { dir: "tools/e2e", run: "npm run lint:tokens -- --selftest" },
      { dir: "tools/e2e", run: "npm run lint:tokens" },
    ],
    why:
      "NOT a divergence since T-054 (T-045-s1) — CI used to spell this as a " +
      "direct `node scripts/lint-tokens.mjs`, which was the same command " +
      "written a second way. It is still the job's FIRST step, ahead of every " +
      "`npm ci`, because `npm run` needs no installed node_modules (it only " +
      "extends PATH), and still TWO steps, because `--selftest` short-circuits " +
      "the walk. The `--` is load-bearing: npm eats a bare flag after a script " +
      "name (T-046, measured on npm 11.12.1).",
  },
  { kind: "verbatim", dir: "lib/parser", cmd: "npm ci" },
  { kind: "verbatim", dir: "lib/parser", cmd: "npx vitest run" },
  { kind: "verbatim", dir: "lib/parser", cmd: "npx tsc --noEmit" },
  { kind: "verbatim", dir: "lib/parser", cmd: "npm run build" },
  {
    kind: "mapped",
    dir: "app",
    cmd: "npm install",
    steps: [{ dir: "app", run: "npm ci" }],
    why: "DIVERGENCE 1: lockfile-exact installs in CI, everywhere.",
  },
  { kind: "verbatim", dir: "app", cmd: "npm run build" },
  { kind: "verbatim", dir: "app", cmd: "npm test" },
  { kind: "verbatim", dir: "app/src-tauri", cmd: "cargo test" },
  // THE GRAPH-CURRENCY GATE (T-054), placed immediately after the cargo
  // suite: the suite is what builds the crate, and a stale graph is news
  // before the audit spends a minute installing a tool. It is VERBATIM on
  // purpose — the `--root ../..` is part of the documented command, not a
  // CI adaptation, because without it the default root is the current
  // directory and the check reports the graph MISSING and exits 1, which
  // is a FALSE RED that reads exactly like staleness.
  {
    kind: "verbatim",
    dir: "app/src-tauri",
    cmd: "cargo run -p supertaskr-index -- index --check --root ../..",
  },
  {
    kind: "ci-only",
    step: {
      dir: "app/src-tauri",
      run: "command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit --locked",
    },
    why:
      "the dev-tool setup, guarded (T-153-s13): the cargo cache saves " +
      "~/.cargo/bin, so the run after the first install restores the binary " +
      "and a bare `cargo install` refuses with `binary already exists` — " +
      "which stopped every run on this Cargo.lock at this step. A restored " +
      "binary is the happy path. A dev tool, never a repo dep (T-009-s3).",
  },
  { kind: "verbatim", dir: "app/src-tauri", cmd: "cargo audit" },
  { kind: "verbatim", dir: "tools/e2e", cmd: "npm ci" },
  // THE DOCS GATE (T-090), immediately after tools/e2e's install — the
  // earliest slot its own dependency allows. It CANNOT hold the token
  // lint's bare-checkout position: `token-scan.mjs` is zero-dependency
  // and `npm run` only extends PATH, while `docs-gate.mjs` imports
  // `yaml`, chosen because it is the same package lib/parser parses cards
  // with (T-057). The step runs the gate's WHOLE-TREE half and judges no
  // diff — a workflow has no "merge's diff" to be handed. VERBATIM, and
  // the named command IS the point: this gate was a hand-run ritual with
  // no step at all because T-084's fence could not reach ci.yml
  // (T-084-s2), which is the whole of why nobody was obliged to run it.
  { kind: "verbatim", dir: "tools/e2e", cmd: "npm run lint:docs" },
  { kind: "verbatim", dir: "tools/e2e", cmd: "npm run typecheck" },
  // THE CENSUS-CURRENCY GATE (T-153-s8), immediately after the types and
  // before the browser download. docs/CAPABILITIES.md is GENERATED from
  // the test names in this directory and nothing on the merge path ever
  // asked whether the committed bytes still matched a fresh generation:
  // the census went stale, was regenerated by hand at a checkpoint, and
  // went stale again with no instrument in between. Like the DOCS GATE
  // it cannot hold the token lint's bare-checkout seat — though for a
  // different reason, worth writing down because the obvious one is
  // wrong.
  // `capabilities.mjs` imports NO package and does run on an uninstalled
  // worktree; but it resolves a templated test name's iterable by
  // importing a `.mjs` out of tests/, and scripts there import `yaml`.
  // The bare-checkout property therefore belongs to the SPEC TREE, not
  // to the script, and a spec edit could take it away from three layers
  // off. VERBATIM: `--check` is the documented command, not a CI
  // adaptation of it.
  { kind: "verbatim", dir: "tools/e2e", cmd: "npm run capabilities:check" },
  {
    kind: "ci-only",
    step: { dir: "tools/e2e", run: "npx playwright install --with-deps chromium" },
    why:
      "DIVERGENCE 2: the local one-time form is `npx playwright install " +
      "chromium`; `--with-deps` adds the Linux system libs a fresh runner lacks.",
  },
  { kind: "verbatim", dir: "tools/e2e", cmd: "npm test" },
  {
    kind: "mapped",
    dir: "tools/e2e",
    cmd: "npm run boot:check",
    steps: [{ dir: "tools/e2e", run: "xvfb-run -a npm run boot:check" }],
    why:
      "NOT a divergence since T-054 (T-045-s1) — CI used to spell this as " +
      "`xvfb-run -a node tools/e2e/scripts/tauri-boot-check.mjs` from the repo " +
      "root, a second spelling of the documented command. The xvfb WRAPPER is " +
      "real and stays: a headless runner has no display. Both scripts resolve " +
      "the repo root from import.meta.url rather than process.cwd(), so " +
      "invoking them through npm from tools/e2e is behaviourally identical. " +
      "LAST, so the cargo cache warms its build.",
  },
];

/**
 * CONVENTIONS commands that are deliberately NOT CI steps. Listed so the
 * doc's list is fully accounted for — an unlisted command is a hole, and
 * a silently-dropped one is the hole this task exists to close. Asserted
 * ABSENT from the workflow below, not merely omitted here.
 */
const LOCAL_ONLY: { dir: string; cmd: string; why: string }[] = [
  {
    dir: "app",
    cmd: "npm run tauri dev",
    why: "opens a real window; the xvfb boot step covers the dev path in CI.",
  },
  {
    dir: "app",
    cmd: "npm run tauri build",
    why: "packages a bundle — minutes of work no gate reads (T-046-s3).",
  },
  {
    dir: "app/src-tauri",
    cmd: "cargo run -p supertaskr-index -- index --watch --root ../..",
    why:
      "a watcher: it blocks until stopped, so a CI step invoking it would hang " +
      "until the job timeout. `index --check` is the one-shot form and IS a " +
      "step (T-054).",
  },
  {
    dir: "app/src-tauri",
    cmd: "cargo run -p supertaskr-index -- arch --root ../..",
    why:
      "a REPORTER, not a gate: it reads the COMMITTED graph and always exits 0 " +
      "(ADR-014). Its gating form is `arch drift --fail-on <sev>`, deliberately " +
      "unwired while the registry carries live undeclared edges — wiring it " +
      "would red CI on drift the architect is holding open on purpose (T-054).",
  },
  {
    dir: "app/src-tauri",
    cmd: "cargo run -p supertaskr-index -- arch cycles --root ../..",
    why:
      "a REGISTRY-ONLY verdict whose red is DESIGNED to stand: the declared " +
      "C-08 <-> C-09 cycle is held open until T-127-s1, so a CI step would " +
      "red every run on a ruling deliberately kept open. The ENFORCING copy " +
      "is cargo test's exact-set cycle census (T-127; documented at ADR-019 " +
      "phase 5, discharging T-127-s5).",
  },
  {
    dir: "app/src-tauri",
    cmd: "cargo run -p supertaskr-index -- arch blast <path|slug> --root ../..",
    why:
      "a REPORTER like `arch`: derives dependents from the committed graph " +
      "at read time and gates nothing (T-135 Half A; documented at ADR-019 " +
      "phase 5).",
  },
  {
    dir: "tools/e2e",
    cmd: "npm run capabilities",
    why:
      "T-153-s8. The GENERATOR of docs/CAPABILITIES.md, and the command " +
      "`capabilities:check` prints by name when it reds — which is exactly why it " +
      "is documented and exactly why it must not be a step. A generator run inside " +
      "the runner rewrites the file the check judges, exits 0, and certifies its " +
      "own output: the known-vacuous keeper, wearing the keeper's costume. The " +
      "regeneration belongs in a COMMIT, and in the same commit as whatever moved " +
      "a test name — otherwise the check reds on the next lane, layers from its " +
      "cause. Its `--check` half IS a step, the way `index --check` is the one-shot " +
      "form of a command whose other form is local-only.",
  },
  {
    dir: "tools/e2e",
    cmd: "npm run boot:orphan-drill",
    why:
      "T-061-s5, ruled at T-090. The drill was SHIPPED at T-061 with a four-code " +
      "contract and CONVENTIONS never named it, so a shipped procedure went " +
      "unmet — and naming it forced this disposition, because the derivation " +
      "makes every documented command either a step or an argued exclusion. " +
      "NOT a step: it opens a window and builds the app, roughly doubling the " +
      "boot step's cost, and it deliberately SIGKILLs a process mid-boot, which " +
      "on a shared runner is a different risk profile from a laptop. It is a " +
      "REGRESSION drill rather than a release gate — the property it pins " +
      "cannot drift without somebody editing tauri-boot-check.mjs's exit path — " +
      "so it takes the disposition `index --watch` and `arch` already have.",
  },
];

/**
 * Run steps that are infrastructure, not CONVENTIONS commands: the job
 * has to exist before it can invoke anything. Enumerated so that "every
 * run step is either derived from the doc or argued here" can be a real
 * assertion — otherwise a step could be smuggled into ci.yml unread.
 */
const INFRASTRUCTURE_STEPS: { match: RegExp; why: string }[] = [
  { match: /^sudo apt-get update/, why: "the Tauri v2 Linux prerequisites + xvfb." },
  { match: /^rustc --version/, why: "records the runner's preinstalled toolchain." },
  {
    match: /^df -h \./,
    why:
      "T-278: the runner's own disk, read on both sides of the e2e lane and " +
      "floored before it. NOT a CONVENTIONS command and deliberately not one — " +
      "nothing here is a suite, a lint or a gate over the TREE; it is a reading " +
      "of the MACHINE, which is the one thing the doc's per-package command " +
      "bullets cannot be about. What each of the two steps has to look like is " +
      "derived by `diskGuardProblems` below, so this entry accounts for them " +
      "without becoming the place their shape is written down.",
  },
];

/** The doc's own command list, flattened. */
function docCommandMap(section: string): Map<string, { dir: string; cmd: string }> {
  const map = new Map<string, { dir: string; cmd: string }>();
  for (const { dir, commands } of commandBullets(section)) {
    for (const cmd of commands) map.set(docKey(dir, cmd), { dir, cmd });
  }
  return map;
}

/** The four per-package bullets the section must carry, in order. */
const DOC_DIRS = ["lib/parser", "app", "app/src-tauri", "tools/e2e"];

/**
 * The expected workflow steps, DERIVED from docs/CONVENTIONS.md, plus
 * every reason the derivation could not be trusted. `problems` empty is
 * the assertion; each entry names the side that moved and what to do.
 */
export function deriveExpectedSteps(md: string): { steps: Step[]; problems: string[] } {
  const section = buildAndTestSection(md);
  const ci = ciBullet(section);
  const doc = docCommandMap(section);
  const problems: string[] = [];
  if (ci === "") {
    problems.push(
      'docs/CONVENTIONS.md "Build & test" has no `- CI (.github/workflows/' +
        "ci.yml)` bullet — that bullet is where every divergence between the " +
        "documented commands and the workflow has to be written down.",
    );
  }

  // 0. The parse is not vacuous. Four bullets, in order, each with
  //    commands — a restructured section must fail loudly here rather
  //    than quietly derive an empty expectation every workflow satisfies.
  //    FIRST the shapes the parse cannot see at all (T-045-s4): those
  //    three attacks were the only silent ones, and silence is worse
  //    than a wrong expectation because nothing points at it.
  problems.push(...structuralProblems(section));
  const dirs = commandBullets(section).map((b) => b.dir);
  if (JSON.stringify(dirs) !== JSON.stringify(DOC_DIRS)) {
    problems.push(
      `docs/CONVENTIONS.md "Build & test" no longer carries exactly the four ` +
        `\`run from <dir>/:\` command bullets ${JSON.stringify(DOC_DIRS)} — found ` +
        `${JSON.stringify(dirs)}. The derivation reads those bullets; a fifth ` +
        `package or a renamed one is a deliberate update to this spec.`,
    );
  }
  for (const { dir, commands } of commandBullets(section)) {
    if (commands.length === 0) {
      problems.push(
        `docs/CONVENTIONS.md "Build & test" lists no commands for [${dir}] — the ` +
          "list ends at the first `·` segment that does not open with a backtick, " +
          "so a command that lost its backticks is invisible to CI parity.",
      );
    }
  }

  // 1. Every command the doc lists is accounted for, and every command
  //    this spec accounts for is still in the doc. Both directions: the
  //    first catches a NEW command CI never runs, the second catches a
  //    REWORDED or DELETED one CI still runs (T-045 criterion 2).
  const claimed = new Map<string, string>();
  for (const entry of CI_SEQUENCE) {
    if (entry.kind !== "ci-only") claimed.set(docKey(entry.dir, entry.cmd), entry.kind);
  }
  for (const entry of LOCAL_ONLY) claimed.set(docKey(entry.dir, entry.cmd), "local-only");
  for (const key of doc.keys()) {
    if (!claimed.has(key)) {
      problems.push(
        `docs/CONVENTIONS.md "Build & test" lists ${key}, which this spec has no ` +
          "entry for — add it to CI_SEQUENCE (verbatim or mapped, with the " +
          "workflow step) or to LOCAL_ONLY with the reason CI does not run it.",
      );
    }
  }
  for (const key of claimed.keys()) {
    if (!doc.has(key)) {
      problems.push(
        `this spec expects ${key}, which docs/CONVENTIONS.md "Build & test" no ` +
          "longer lists — the doc is the source of truth: a reworded or removed " +
          "command means the workflow and this spec both need the same edit.",
      );
    }
  }

  // 2. Every disposition that is not "verbatim" is documented in the DOC's
  //    CI bullet, not only argued here. A mapping this file knows about and
  //    CONVENTIONS does not is exactly the untracked difference criterion 1
  //    forbids — and the CI bullet is the one place its reader will look.
  for (const entry of CI_SEQUENCE) {
    if (entry.kind === "verbatim") continue;
    const steps = entry.kind === "mapped" ? entry.steps : [entry.step];
    for (const step of steps) {
      if (!ci.includes(`\`${step.run}\``)) {
        problems.push(
          `the workflow runs \`${step.run}\` but docs/CONVENTIONS.md "Build & ` +
            'test" never mentions it — an untracked divergence. Document it in ' +
            "the CI bullet (which enumerates them) so both sides say the same thing.",
        );
      }
    }
  }
  //    Same rule for the commands CI deliberately skips: a reader of the CI
  //    bullet must be able to see that they are skipped on purpose.
  for (const entry of LOCAL_ONLY) {
    if (!ci.includes(`\`${entry.cmd}\``)) {
      problems.push(
        `this spec says CI deliberately does not run \`${entry.cmd}\` (${entry.why}) ` +
          'but docs/CONVENTIONS.md\'s CI bullet does not say so — an omission a ' +
          "reader cannot tell from a mistake.",
      );
    }
  }

  // 3. The expected steps, with every verbatim command taken from the
  //    DOC's own text rather than restated here.
  const steps: Step[] = [];
  for (const entry of CI_SEQUENCE) {
    if (entry.kind === "ci-only") {
      steps.push(entry.step);
      continue;
    }
    const fromDoc = doc.get(docKey(entry.dir, entry.cmd));
    if (fromDoc === undefined) continue; // already reported above
    if (entry.kind === "verbatim") steps.push({ dir: fromDoc.dir, run: fromDoc.cmd });
    else steps.push(...entry.steps);
  }
  return { steps, problems };
}

/** Commands CONVENTIONS lists that must NOT appear as workflow steps. */
function localOnlySteps(): Step[] {
  return LOCAL_ONLY.map((e) => ({ dir: e.dir, run: e.cmd }));
}

// ── reading .github/workflows/ci.yml ───────────────────────────────────

/** Tauri v2 Linux prerequisites the apt step must install. */
const APT_PACKAGES = [
  "libwebkit2gtk-4.1-dev",
  "build-essential",
  "libxdo-dev",
  "libssl-dev",
  "libayatana-appindicator3-dev",
  "librsvg2-dev",
  "xvfb",
];

function loadWorkflow(): { raw: string; doc: Record<string, unknown>; steps: WorkflowStep[] } {
  const file = path.join(repoRoot, ".github", "workflows", "ci.yml");
  const raw = readFileSync(file, "utf8");
  const doc = parse(raw) as Record<string, unknown>;
  const jobs = doc.jobs as Record<string, { steps: WorkflowStep[] }>;
  const jobNames = Object.keys(jobs);
  expect(jobNames, "one ubuntu job (plan §7)").toEqual(["linux"]);
  return { raw, doc, steps: jobs.linux!.steps };
}

function runSteps(steps: WorkflowStep[]): Step[] {
  return steps
    .filter((s) => s.run !== undefined)
    .map((s) => ({ dir: s["working-directory"], run: s.run! }));
}

// ── the tests ──────────────────────────────────────────────────────────

test("ci.yml is valid YAML with the one pinned ubuntu job", () => {
  const { doc, steps } = loadWorkflow();

  // `on:` parses as YAML true — normalize.
  const on = (doc.on ?? doc[true as unknown as string]) as Record<string, unknown>;
  expect(Object.keys(on).sort()).toEqual(["pull_request", "push", "workflow_dispatch"]);
  expect((on.push as { branches: string[] }).branches).toEqual(["main"]);

  const concurrency = doc.concurrency as { group: string; "cancel-in-progress": boolean };
  expect(concurrency.group).toContain("${{ github.ref }}");
  expect(concurrency["cancel-in-progress"]).toBe(true);

  const job = (doc.jobs as Record<string, Record<string, unknown>>).linux!;
  expect(job["runs-on"], "pinned runner, not -latest").toBe("ubuntu-24.04");
  expect(job["timeout-minutes"]).toBe(45);
  expect(steps.length).toBeGreaterThan(0);
});

test("the expected commands derive cleanly from docs/CONVENTIONS.md", () => {
  const { steps, problems } = deriveExpectedSteps(readConventions());
  expect(
    problems,
    "the workflow's expected commands are PARSED out of docs/CONVENTIONS.md " +
      '"Build & test" — these are the ways the doc and this spec disagree',
  ).toEqual([]);
  // A FLOOR on the derivation itself, never a count — the doc gains
  // commands (T-054 added three supertaskr-index ones; T-090 added
  // `npm run lint:docs` as a step and `npm run boot:orphan-drill` as an
  // argued exclusion), and a floor stays true while an equality would
  // make every such edit a two-file change for no property.
  expect(steps.length, "derived step count").toBeGreaterThanOrEqual(19);
});

test("every CONVENTIONS command is a step, verbatim and in CI order", () => {
  const { steps: expected } = deriveExpectedSteps(readConventions());
  const actual = runSteps(loadWorkflow().steps);

  // Every derived command appears verbatim as its own step...
  for (const want of expected) {
    const found = actual.some((s) => s.dir === want.dir && s.run === want.run);
    expect.soft(found, `missing verbatim step: ${stepKey(want)}`).toBe(true);
  }

  // ...and in order: filtering the workflow's run steps to the expected
  // set must reproduce the expected sequence exactly.
  const filtered = actual.filter((s) => expected.some((w) => w.dir === s.dir && w.run === s.run));
  expect(filtered).toEqual(expected);
});

test("the workflow runs nothing beyond the derived commands and its infrastructure", () => {
  const { steps: expected } = deriveExpectedSteps(readConventions());
  const actual = runSteps(loadWorkflow().steps);

  const unaccounted = actual.filter(
    (s) =>
      !expected.some((w) => w.dir === s.dir && w.run === s.run) &&
      !INFRASTRUCTURE_STEPS.some((i) => i.match.test(s.run)),
  );
  expect(
    unaccounted.map(stepKey),
    "ci.yml is a THIN INVOKER of the CONVENTIONS commands — a step that is " +
      "neither derived from the doc nor listed as infrastructure is a command " +
      "nobody documented",
  ).toEqual([]);

  // The commands CONVENTIONS lists that CI deliberately does not run must
  // actually be absent — LOCAL_ONLY is a claim, so it gets checked.
  const smuggled = localOnlySteps().filter((w) =>
    actual.some((s) => s.dir === w.dir && s.run === w.run),
  );
  expect(
    smuggled.map(stepKey),
    "these are listed as local-only in this spec but the workflow runs them",
  ).toEqual([]);
});

test("every `uses:` is pinned by a full 40-hex commit SHA", () => {
  const { steps } = loadWorkflow();
  const uses = steps.filter((s) => s.uses !== undefined).map((s) => s.uses!);
  expect(uses.length).toBeGreaterThanOrEqual(3); // checkout, setup-node, cache x2
  for (const ref of uses) {
    expect(ref, `unpinned action: ${ref}`).toMatch(/^[\w./-]+@[0-9a-f]{40}$/);
  }
});

test("the xvfb boot step runs the documented boot check with the webkit workaround", () => {
  const { steps } = loadWorkflow();
  const boot = steps.find((s) => s.run?.includes("boot:check"));
  expect(boot, "boot step present").toBeDefined();
  // T-054: the wrapper is real, what it wraps is the documented command.
  expect(boot!.run).toBe("xvfb-run -a npm run boot:check");
  expect(boot!["working-directory"], "npm resolves the script from tools/e2e").toBe("tools/e2e");
  expect(boot!.env?.WEBKIT_DISABLE_DMABUF_RENDERER).toBe("1");
  // LAST step — the cargo cache from the test step warms its build.
  expect(steps[steps.length - 1]).toBe(boot);
});

test("the apt step installs the Tauri v2 webkit2gtk set + xvfb", () => {
  const { steps } = loadWorkflow();
  const apt = steps.find((s) => s.run?.includes("apt-get install"));
  expect(apt, "apt step present").toBeDefined();
  for (const pkg of APT_PACKAGES) {
    expect(apt!.run, `apt step must install ${pkg}`).toContain(pkg);
  }
});

// ── the runner's disk around the e2e lane (T-278) ──────────────────────
//
// THE RED THIS SECTION KEEPS. Four consecutive runs on main died inside
// the e2e lane of ENOSPC — 34300080330 (a6355bb, twice), 34304932475
// (5775ac0) and 34306871214 (6c46872), against 683cd60 as the last green
// runner — and in every one of them the FIRST red body was the same one:
// brief.spec's "THE ARM LEAVES EXACTLY WHAT THE EIGHT HAND STEPS LEAVE,
// file for file", ordinal 64 of 706, reporting the arm stopping inside its
// ritual with exit 3 (step 4, the fence, in two attempts; step 6, the
// bench, in the other two). The runner's reason appeared ONCE, indented inside that
// body's stderr, and nowhere else in the job's 4103 log lines. A disk red
// wearing a landing-gate defect's clothes, three runs running.
//
// ci.yml now reads the disk on both sides of the lane and REFUSES below a
// stated floor. That is two steps and a number, and each of the three
// rots silently in its own way: a reading that drifts away from the lane
// it guards measures a different moment; an `if:` dropped from the second
// one means the disk is only ever read after a GREEN lane, which is the
// run nobody needed it for; a floor edited in the `env:` and left stale
// in the step's NAME publishes one figure and tests another. So the shape
// is DERIVED here rather than asserted once, and `problems` empty is the
// assertion — the idiom `deriveExpectedSteps` and `stepPackageProblems`
// already use in this file.
//
// AND THE FLOOR IS NOT TRANSCRIBED. Nothing below states 2 GiB. The
// derivation reads the figure out of the step's `env:` and requires the
// step's NAME to state the SAME one; what it pins is the AGREEMENT, so
// raising the floor stays a one-line edit to ci.yml and a floor raised in
// one of the two places reds. A number copied into a spec is the mirror
// failure T-045 already took out of this file once.

/** The e2e lane step itself — the anchor both disk steps are placed against. */
const LANE_STEP: Step = { dir: "tools/e2e", run: "npm test" };

/** The one place ci.yml writes the floor down. */
const DISK_FLOOR_ENV = "E2E_DISK_FLOOR_GIB";

/** The before-step's name, which must STATE the floor its `env:` declares. */
const DISK_BEFORE_NAME = /^runner disk before the e2e lane \(floor (\d+) GiB\)$/;

/** The after-step's name; it carries no figure, so it is a literal. */
const DISK_AFTER_NAME = "runner disk after the e2e lane";

/** The two `df` readings the before-step owes: the workspace AND the fixtures' own tree. */
const DISK_PROBES = ["df -h .", "df -h /tmp"] as const;

/** Everything wrong with the BEFORE step, given that it is in the right place. */
function diskFloorProblems(step: WorkflowStep, name: string): string[] {
  const problems: string[] = [];
  const stated = Number(DISK_BEFORE_NAME.exec(name)?.[1]);
  const declared = step.env?.[DISK_FLOOR_ENV];
  const run = step.run ?? "";

  if (declared === undefined) {
    problems.push(
      `\`${name}\` declares no \`${DISK_FLOOR_ENV}\` in its \`env:\`. The floor is ` +
        "written ONCE, in that key, and the step's name repeats it for `gh` to " +
        "report; a step that only prints the disk is the half of T-278 a print " +
        "already gave.",
    );
  } else if (!/^[1-9][0-9]*$/.test(declared)) {
    problems.push(
      `\`${name}\` declares \`${DISK_FLOOR_ENV}: "${declared}"\`, which is not a ` +
        "positive whole number of GiB. A floor of zero — or of a word, which the " +
        "shell reads as zero — can never fire, and a guard that cannot fire is the " +
        "vacuous keeper this suite exists to refuse.",
    );
  } else if (Number(declared) !== stated) {
    problems.push(
      `\`${name}\` states ${String(stated)} GiB in its NAME and declares ` +
        `${declared} in \`${DISK_FLOOR_ENV}\`. The name is what a seat reads — ` +
        "`gh` reports the step that failed by name, and push-guard.mjs looks it " +
        "up — while the env is what the shell tests, so the two disagreeing is a " +
        "published figure nobody enforces.",
    );
  }

  if (step["working-directory"] !== LANE_STEP.dir) {
    problems.push(
      `\`${name}\` declares \`working-directory: ${String(step["working-directory"])}\` ` +
        `rather than \`${String(LANE_STEP.dir)}\`. It reads \`df -h .\`, so its cwd IS ` +
        "one of its two measurements, and it is the lane's cwd this step is about.",
    );
  }

  for (const probe of DISK_PROBES) {
    if (!run.includes(probe)) {
      problems.push(
        `\`${name}\` never runs \`${probe}\`. Both readings are owed: the workspace ` +
          "is where the checkout, the installs and the built target sit, and /tmp is " +
          "where every fixture in the lane builds its scratch repositories — on a " +
          "hosted runner they are usually one filesystem, and the run that proves " +
          "they are not is the run this step exists for.",
      );
    }
  }

  if (!run.includes(DISK_FLOOR_ENV)) {
    problems.push(
      `\`${name}\` never reads \`${DISK_FLOOR_ENV}\` in its script, so the floor it ` +
        "declares is decorative: the env key is set, the name advertises it, and " +
        "nothing compares it to anything.",
    );
  }

  if (!/\bexit 1\b/.test(run)) {
    problems.push(
      `\`${name}\` never exits non-zero. Printing the disk makes the reason FINDABLE ` +
        "by whoever opens the log; the criterion is that the JOB says it, at a step " +
        "whose name is the diagnosis, before a body can wear a failure that was " +
        "never its own.",
    );
  }

  return problems;
}

/**
 * Where ci.yml's disk guard has come apart. `problems` empty is the
 * assertion; each entry names the step it is about and what to do.
 *
 * Takes the STEP LIST as its argument, the way `stepPackageProblems`
 * takes its files, so a fixture can feed it a mutated copy — no body in
 * this file writes to `.github/`.
 */
export function diskGuardProblems(steps: WorkflowStep[]): string[] {
  const problems: string[] = [];
  const laneIndex = steps.findIndex(
    (s) => s["working-directory"] === LANE_STEP.dir && s.run?.trim() === LANE_STEP.run,
  );
  if (laneIndex < 0) {
    return [
      `.github/workflows/ci.yml has no \`[${String(LANE_STEP.dir)}] ${LANE_STEP.run}\` ` +
        "step, so there is nothing for the disk guard to be placed against. That " +
        "step is the e2e lane T-278's ENOSPC red ran inside; without it every " +
        "check below would pass by having nothing to check.",
    ];
  }

  const before = laneIndex > 0 ? steps[laneIndex - 1] : undefined;
  const beforeName = before?.name;
  if (before === undefined || beforeName === undefined || !DISK_BEFORE_NAME.test(beforeName)) {
    const elsewhere = steps.findIndex((s) => s.name !== undefined && DISK_BEFORE_NAME.test(s.name));
    problems.push(
      "the step immediately before the e2e lane is " +
        (beforeName === undefined ? "unnamed or absent" : `\`${beforeName}\``) +
        `, not the disk read T-278 put there (a name matching ${String(DISK_BEFORE_NAME)}). ` +
        (elsewhere < 0
          ? "NO step in the file carries that name: the floor is gone, and an ENOSPC " +
            "inside the lane goes back to arriving as one body's stderr."
          : `The step sits at index ${String(elsewhere)} instead of ` +
            `${String(laneIndex - 1)} — a disk reading taken anywhere but immediately ` +
            "before the lane measures a different moment than the one that fills, and " +
            "everything installed in between is unaccounted for."),
    );
  } else {
    problems.push(...diskFloorProblems(before, beforeName));
  }

  const after = steps[laneIndex + 1];
  if (after === undefined || after.name !== DISK_AFTER_NAME) {
    problems.push(
      `the step immediately after the e2e lane is ${after?.name === undefined ? "unnamed or absent" : `\`${after.name}\``}` +
        `, not \`${DISK_AFTER_NAME}\`. The reading AFTER the lane is what turns a ` +
        "floor into a measurement: it is the only place the job says what the lane " +
        "actually spent, and the only place a leaked fixture can be named.",
    );
  } else {
    if (after.if !== "always()") {
      problems.push(
        `\`${DISK_AFTER_NAME}\` carries \`if: ${String(after.if)}\` rather than ` +
          "`if: always()`. Without it the disk is read only after a GREEN lane — the " +
          "run nobody needs it for — and the red run it exists for skips it.",
      );
    }
    if (after["working-directory"] !== LANE_STEP.dir) {
      problems.push(
        `\`${DISK_AFTER_NAME}\` declares \`working-directory: ` +
          `${String(after["working-directory"])}\` rather than \`${String(LANE_STEP.dir)}\`, ` +
          "so its `df -h .` reads a different tree than the before-step's and the " +
          "pair stops being a before/after of one thing.",
      );
    }
    if (!(after.run ?? "").includes("df -h /tmp")) {
      problems.push(
        `\`${DISK_AFTER_NAME}\` never runs \`df -h /tmp\`, which is the half of the ` +
          "pair that answers what the lane spent where its fixtures live.",
      );
    }
  }

  return problems;
}

test("the runner's disk is read on both sides of the e2e lane, behind a floor that can fire", () => {
  const { steps } = loadWorkflow();
  expect(
    diskGuardProblems(steps),
    "T-278: ci.yml reads the runner's disk before and after the e2e lane and refuses " +
      "below a floor it states once — these are the ways that guard has come apart",
  ).toEqual([]);

  // AND THE PAIR IS NOT THE JOB'S TAIL. The boot step stays last (pinned
  // by the xvfb body above), so the after-reading sits BETWEEN the lane
  // and the boot check. Appending it instead would have been the obvious
  // spelling and the wrong one: `always()` at the end of the job reads a
  // disk the boot check had already moved.
  const laneIndex = steps.findIndex(
    (s) => s["working-directory"] === LANE_STEP.dir && s.run?.trim() === LANE_STEP.run,
  );
  expect(
    laneIndex + 1,
    "the after-reading is not the job's last step — the boot check follows it",
  ).toBeLessThan(steps.length - 1);

  // THE EXECUTING ARM (T-278's verdict, correction 2): `diskGuardProblems`
  // derives that the step CARRIES an `exit 1`; whether the floor can FIRE
  // is a property of the shell, and `if [ … ] && false; then` keeps the
  // token while making it unreachable — every derivation above stayed
  // green against that edit. So the step's own script is run, twice,
  // against a stub `df` on PATH: one KiB above the floor it must exit 0,
  // one KiB below it must exit 1 and say `::error`. The stub answers every
  // `df` spelling the step uses (-h, -i, -Pk) with one POSIX table whose
  // Available column is the figure under test.
  const before = steps[laneIndex - 1]!;
  const gib = Number(before.env?.[DISK_FLOOR_ENV]);
  expect(Number.isInteger(gib) && gib > 0, "the floor step declares an integer GiB floor").toBe(true);
  const floorKib = gib * 1024 * 1024;
  const stubDir = mkdtempSync(path.join(tmpdir(), "t278-stub-df-"));
  try {
    const stub = path.join(stubDir, "df");
    writeFileSync(
      stub,
      "#!/bin/sh\n" +
        'printf "Filesystem 1024-blocks Used Available Capacity Mounted on\\n"\n' +
        'printf "stub 0 0 %s 0%% /\\n" "$STUB_AVAIL_KIB"\n',
    );
    chmodSync(stub, 0o755);
    const runAt = (availKib: number) =>
      spawnSync("bash", ["-e", "-c", before.run ?? ""], {
        cwd: path.join(repoRoot, String(before["working-directory"] ?? ".")),
        env: {
          ...process.env,
          PATH: `${stubDir}:${process.env.PATH ?? ""}`,
          [DISK_FLOOR_ENV]: String(gib),
          STUB_AVAIL_KIB: String(availKib),
        },
        encoding: "utf8",
      });
    const above = runAt(floorKib + 1);
    expect(above.status, `one KiB above the floor the step passes: ${above.stdout}${above.stderr}`).toBe(0);
    const below = runAt(floorKib - 1);
    expect(below.status, `one KiB below the floor the step FAILS: ${below.stdout}${below.stderr}`).toBe(1);
    expect(below.stdout, "and the red names itself as the runner's disk").toContain("::error title=runner disk below the e2e floor");
  } finally {
    rmSync(stubDir, { recursive: true, force: true });
  }
});

test("FIXTURE: six one-edit mutants of the disk guard — deleted, moved, floor stale in the name, floor zero, print-only, `always()` dropped — each red BY NAME", () => {
  const { steps } = loadWorkflow();

  // THE CONTROL. Every mutant below is this list with ONE edit, so a red
  // is the edit and never the scaffolding (method/roles/verifier.md 2b).
  expect(diskGuardProblems(steps), "the real workflow derives clean").toEqual([]);
  const laneIndex = steps.findIndex(
    (s) => s["working-directory"] === LANE_STEP.dir && s.run?.trim() === LANE_STEP.run,
  );
  expect(laneIndex, "the e2e lane step is found").toBeGreaterThan(0);
  const before = steps[laneIndex - 1]!;
  const after = steps[laneIndex + 1]!;

  // (1) THE GUARD DELETED — the state ci.yml was in for every one of the
  //     four red runs.
  const deleted = steps.filter((_, i) => i !== laneIndex - 1);
  expect(diskGuardProblems(deleted).join("\n"), "a deleted floor is named as absent").toContain(
    "NO step in the file carries that name",
  );

  // (2) THE GUARD MOVED to the head of the job, where it would read the
  //     disk before three installs, a cargo build and a browser download.
  const moved = [before, ...steps.filter((_, i) => i !== laneIndex - 1)];
  expect(diskGuardProblems(moved).join("\n"), "a moved reading is named by index").toContain(
    "measures a different moment",
  );

  // (3) THE FLOOR RAISED IN ONE PLACE. The env says 8, the name still
  //     says what it always said — the shape a floor edit takes when the
  //     editor forgets that `gh` reports the NAME.
  const stale = steps.map((s, i) =>
    i === laneIndex - 1 ? { ...s, env: { ...s.env, [DISK_FLOOR_ENV]: "8" } } : s,
  );
  expect(diskGuardProblems(stale).join("\n"), "a half-edited floor names both sides").toContain(
    `declares 8 in \`${DISK_FLOOR_ENV}\``,
  );

  // (4) A FLOOR THAT CANNOT FIRE. Zero is free space every runner has.
  const zero = steps.map((s, i) =>
    i === laneIndex - 1 ? { ...s, env: { ...s.env, [DISK_FLOOR_ENV]: "0" } } : s,
  );
  expect(diskGuardProblems(zero).join("\n"), "a zero floor is refused as vacuous").toContain(
    "can never fire",
  );

  // (5) PRINT-ONLY. The step still reads both filesystems and still
  //     declares the floor; it just stops refusing — which is exactly
  //     what "print the disk" alone would have shipped.
  const printOnly = steps.map((s, i) =>
    i === laneIndex - 1 ? { ...s, run: (s.run ?? "").replace("exit 1", "true") } : s,
  );
  expect(diskGuardProblems(printOnly).join("\n"), "a print-only guard is named").toContain(
    "never exits non-zero",
  );

  // (6) THE `always()` DROPPED from the after-reading — the mutant that
  //     leaves the file looking complete and takes the measurement away
  //     from exactly the run that needed it.
  const { if: _condition, ...unconditional } = after;
  const conditional = steps.map((s, i) => (i === laneIndex + 1 ? unconditional : s));
  expect(diskGuardProblems(conditional).join("\n"), "a dropped condition is named").toContain(
    "the red run it exists for skips it",
  );

  // EACH MUTANT IS ALONE. Six edits, six problem lists, and every one of
  // them carries exactly one entry: a derivation that reds for two
  // reasons at once cannot say which property it was pinning.
  for (const [what, mutated] of [
    ["deleted", deleted],
    ["moved", moved],
    ["stale floor", stale],
    ["zero floor", zero],
    ["print-only", printOnly],
    ["unconditional", conditional],
  ] as const) {
    expect(diskGuardProblems(mutated), `the ${what} mutant reds on ONE property`).toHaveLength(1);
  }
});

// ── fixtures: the derivation actually binds (T-045 criterion 2) ────────
//
// A mutation drill run once by an executor proves an assertion fired that
// night. These are the same drills kept: synthetic CONVENTIONS texts fed
// to the real derivation, re-proven on every lane run. None of them writes
// to the doc — each one mutates a copy in memory.

test("FIXTURE: rewording a command in CONVENTIONS reds the lane, naming both sides", () => {
  const md = readConventions();
  const reworded = md.replace(
    "`npx vitest run` (suite)",
    "`npx vitest run --reporter=dot` (suite)",
  );
  expect(reworded, "the fixture must actually change the doc").not.toBe(md);

  const { steps, problems } = deriveExpectedSteps(reworded);
  const said = problems.join("\n");
  expect(said, "the NEW wording is unaccounted for").toContain(
    "lists [lib/parser] npx vitest run --reporter=dot, which this spec has no entry for",
  );
  expect(said, "the OLD wording is no longer in the doc").toContain(
    "this spec expects [lib/parser] npx vitest run, which docs/CONVENTIONS.md",
  );
  // And the derived expectation drops the stale command rather than
  // quietly keeping it — the mirror's exact failure mode.
  expect(steps.some((s) => s.run === "npx vitest run")).toBe(false);
});

test("FIXTURE: deleting a command from CONVENTIONS reds the lane", () => {
  const md = readConventions();
  const shortened = md.replace("· `npm run typecheck` ", "");
  expect(shortened, "the fixture must actually change the doc").not.toBe(md);

  const { problems } = deriveExpectedSteps(shortened);
  expect(problems.join("\n")).toContain("this spec expects [tools/e2e] npm run typecheck");
});

test("FIXTURE: an undocumented divergence reds the lane", () => {
  const md = readConventions();
  const undocumented = md.replace(
    "`npx playwright install\n  --with-deps chromium`",
    "the browser install",
  );
  expect(undocumented, "the fixture must actually change the doc").not.toBe(md);

  const { problems } = deriveExpectedSteps(undocumented);
  expect(problems.join("\n")).toContain(
    "the workflow runs `npx playwright install --with-deps chromium` but " +
      'docs/CONVENTIONS.md "Build & test" never mentions it',
  );
});

test("FIXTURE: a restructured section fails loudly, never with an empty expectation", () => {
  const md = readConventions();

  // The section renamed away entirely.
  expect(() =>
    deriveExpectedSteps(md.replace("## Build & test", "## Building and testing")),
  ).toThrow(/no non-empty "## Build & test" section/);

  // The bullets still there, but no longer marked `run from <dir>/:`.
  // (`\s+`, not a literal space: one of the four markers wraps across a
  // line in the raw file, which is why the parser normalizes first.)
  const unmarked = md.replace(/run from\s+([A-Za-z0-9._/-]+)\/:/g, "run in $1 like so —");
  const { steps, problems } = deriveExpectedSteps(unmarked);
  expect(problems.join("\n")).toContain("no longer carries exactly the four");
  // Every command the spec claims is now missing from the doc — one
  // complaint each, not silence — and nothing derived from a doc command
  // survives into the expectation. Asserted against the spec's OWN
  // claimed set rather than a transcribed digit: the count was 19 until
  // T-090 added two commands to the doc, and a hard 19 made a
  // conventions-only edit red HERE, three files from its cause.
  const claimedCount = CI_SEQUENCE.filter((e) => e.kind !== "ci-only").length + LOCAL_ONLY.length;
  expect(problems.filter((p) => p.startsWith("this spec expects")).length).toBe(claimedCount);
  expect(steps.map(stepKey)).toEqual([
    "[app/src-tauri] command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit --locked",
    "[tools/e2e] npx playwright install --with-deps chromium",
  ]);
});

// ── fixtures: the SILENT structures now speak (T-045-s4, taken at T-054) ─
//
// T-045's verifier attacked the derivation twenty-four ways. Eighteen red
// loudly, three are correctly tolerated, and THREE were invisible — each
// one a real command arriving in a shape `commandBullets` does not look
// at, each reporting `problems=0` with the step list unchanged. These
// three fixtures are those three attacks, kept. Each asserts BOTH halves:
// the command really is invisible (the derived steps do not move), and
// the lane now says so by NAME.

/** Splice an attack in just after the app/src-tauri bullet. */
const AUDIT_BULLET = "- AUDIT GATE POLICY";
const spliceIntoBuildAndTest = (md: string, attack: string): string =>
  md.replace(AUDIT_BULLET, attack + AUDIT_BULLET);

test("FIXTURE: an indented sub-bullet is named, not silently swallowed", () => {
  const md = readConventions();
  const attacked = spliceIntoBuildAndTest(md, "  - `cargo clippy -- -D warnings` (indented)\n");
  expect(attacked, "the fixture must actually change the doc").not.toBe(md);

  const before = deriveExpectedSteps(md);
  const after = deriveExpectedSteps(attacked);

  // The invisibility itself, pinned: the doc grew a command and the
  // expectation did not move by one step. THAT is why silence was wrong.
  expect(after.steps.map(stepKey), "the smuggled command is genuinely unread").toEqual(
    before.steps.map(stepKey),
  );
  expect(after.problems.join("\n")).toContain("is an INDENTED BULLET");
  expect(after.problems.join("\n")).toContain("cargo clippy -- -D warnings");
});

test("FIXTURE: an indented sub-bullet with its OWN `run from` marker is named", () => {
  const md = readConventions();
  const attacked = spliceIntoBuildAndTest(
    md,
    "  - extras (T-054 fixture), run from tools/extra/: `npm run smuggled`\n",
  );
  expect(attacked, "the fixture must actually change the doc").not.toBe(md);

  const before = deriveExpectedSteps(md);
  const after = deriveExpectedSteps(attacked);

  expect(after.steps.map(stepKey), "the smuggled bullet is genuinely unread").toEqual(
    before.steps.map(stepKey),
  );
  // The nastiest of the three: a whole PACKAGE bullet arrives and the
  // four-bullet guard cannot see it either, so the loudest check in the
  // derivation stays quiet. Assert that quiet, so this fixture cannot
  // pass for the wrong reason.
  expect(
    after.problems.filter((p) => p.includes("no longer carries exactly the four")),
    "the four-bullet guard is blind to an indented marker — that is the point",
  ).toEqual([]);
  expect(after.problems.join("\n")).toContain("is an INDENTED BULLET");
  expect(after.problems.join("\n")).toContain("run from <dir>/:` marker of its own");
});

test("FIXTURE: a fenced block after a bullet is named, not read as prose", () => {
  const md = readConventions();
  const attacked = spliceIntoBuildAndTest(md, "  ```\n  cargo clippy -- -D warnings\n  ```\n");
  expect(attacked, "the fixture must actually change the doc").not.toBe(md);

  const before = deriveExpectedSteps(md);
  const after = deriveExpectedSteps(attacked);

  expect(after.steps.map(stepKey), "the fenced command is genuinely unread").toEqual(
    before.steps.map(stepKey),
  );
  const fenceProblems = after.problems.filter((p) => p.includes("carries a CODE FENCE"));
  expect(fenceProblems.length, "both fence lines are flagged").toBe(2);
  expect(fenceProblems[0]).toContain("never looks inside a fence");
});

// ── the retracted sentence, from both sides (T-090, absorbing T-084-s2) ─
//
// CONVENTIONS' CI bullet used to say this derivation "is silent in
// exactly ONE case, a command the DOC gains that the spec does not yet
// claim". That is the case it is LOUDEST about, and the first fixture
// below is the disproof kept as a body rather than as a paragraph.
//
// The corrected sentence makes a second claim — that what IS silent is a
// SHAPE the derivation cannot see, and that the one shape still unnamed
// is a command written into a bullet carrying no `run from <dir>/:`
// marker. That claim is a liability in prose and evidence here, so the
// second fixture measures it. Both were measured while T-090 was built;
// neither is transcribed from another document.

test("FIXTURE: a command the DOC gains that the spec does not claim reds BY NAME", () => {
  const md = readConventions();
  // Spliced into a bullet the derivation DOES read, in the doc's own
  // typography, so the command genuinely arrives in the command list.
  const gained = md.replace("· `npm run typecheck` ", "· `npm run typecheck` · `npm run smuggled` ");
  expect(gained, "the fixture must actually change the doc").not.toBe(md);

  const before = deriveExpectedSteps(md);
  const after = deriveExpectedSteps(gained);

  // NOT SILENT: the problem names the command and both dispositions.
  expect(after.problems.join("\n")).toContain(
    "lists [tools/e2e] npm run smuggled, which this spec has no entry for",
  );
  expect(after.problems.join("\n")).toContain("add it to CI_SEQUENCE");
  expect(after.problems.join("\n")).toContain("or to LOCAL_ONLY");
  // And the derivation refuses to invent a step for it — the doc grew a
  // command, the expectation did not, and the lane said so. Both halves,
  // because "it complained" and "it did not silently expect a new step"
  // are different properties and only one of them was ever in doubt.
  expect(after.steps.map(stepKey)).toEqual(before.steps.map(stepKey));
  expect(before.problems, "the live doc derives cleanly").toEqual([]);
});

test("FIXTURE: the shape that IS silent — a command in a bullet with no `run from` marker", () => {
  const md = readConventions();
  // The AUDIT GATE POLICY bullet is prose about a policy: it carries no
  // `run from <dir>/:` marker, so `commandBullets` never looks at it,
  // and it is neither indented nor fenced, so `structuralProblems` has
  // nothing to say either. A command written here is invisible to every
  // loop in the derivation — by construction, because the marker is what
  // makes a bullet a command list.
  const attacked = md.replace(
    "- AUDIT GATE POLICY",
    "- AUDIT GATE POLICY: run `cargo audit --deny warnings` first.",
  );
  expect(attacked, "the fixture must actually change the doc").not.toBe(md);

  const before = deriveExpectedSteps(md);
  const after = deriveExpectedSteps(attacked);

  // THE SILENCE, PINNED. Not "we think this is quiet" — the problems are
  // empty and the step list has not moved, which together are exactly
  // what "the doc grew a command and nothing noticed" means.
  expect(after.problems, "this shape is genuinely silent — that is the finding").toEqual([]);
  expect(after.steps.map(stepKey)).toEqual(before.steps.map(stepKey));
  // The positive control, so the fixture cannot pass because the splice
  // failed: the same command in a bullet the derivation DOES read is
  // loud. Without this, a typo in the replace above reads as silence.
  const control = deriveExpectedSteps(
    md.replace("· `npm run typecheck` ", "· `npm run typecheck` · `cargo audit --deny warnings` "),
  );
  expect(control.problems.join("\n")).toContain(
    "lists [tools/e2e] cargo audit --deny warnings, which this spec has no entry for",
  );
});

test("FIXTURE: a middle dot inside a parenthetical drops every command behind it", () => {
  // The typographic rule's own cost, DERIVED rather than transcribed.
  // CONVENTIONS states it as a DELTA (five commands since ADR-019 phase
  // 5 added `arch cycles` and `arch blast` behind the separator; it was
  // three from T-054 through T-090) because the endpoints move whenever
  // the doc gains a command. A card that quotes endpoints goes stale;
  // this asks the parser.
  const md = readConventions();
  const truncated = md.replace(
    "(T-014's\n  GRAPH-CURRENCY GATE, and a CI step since T-054 — exit 0 current, 1",
    "(T-014's\n  GRAPH-CURRENCY GATE, and a CI step since T-054 · exit 0 current, 1",
  );
  expect(truncated, "the fixture must actually change the doc").not.toBe(md);

  const count = (text: string): number =>
    commandBullets(buildAndTestSection(text)).reduce((n, b) => n + b.commands.length, 0);
  const exposed = count(md);
  const afterTruncation = count(truncated);
  expect(exposed - afterTruncation, "five commands leave CI parity").toBe(5);
  // WHICH five, by name — a delta of 5 could be any five, and the
  // five that vanish are the ones BEHIND the separator in that bullet.
  const names = (text: string): string[] =>
    commandBullets(buildAndTestSection(text)).flatMap((b) => b.commands.map((c) => docKey(b.dir, c)));
  const lost = names(md).filter((k) => !names(truncated).includes(k));
  expect(lost).toEqual([
    "[app/src-tauri] cargo audit",
    "[app/src-tauri] cargo run -p supertaskr-index -- index --watch --root ../..",
    "[app/src-tauri] cargo run -p supertaskr-index -- arch --root ../..",
    "[app/src-tauri] cargo run -p supertaskr-index -- arch cycles --root ../..",
    "[app/src-tauri] cargo run -p supertaskr-index -- arch blast <path|slug> --root ../..",
  ]);
  // And it is LOUD in this direction, which is the half the retracted
  // sentence got right: every command the spec still claims reds by name.
  expect(deriveExpectedSteps(truncated).problems.join("\n")).toContain(
    "this spec expects [app/src-tauri] cargo audit",
  );
});

// ── the OTHER reader of this workflow: the push guard (T-237-s3) ───────
//
// T-237 gave `.github/workflows/ci.yml` a second reader that nothing in
// this file knew about. At push time `.claude/hooks/push-guard.mjs`
// asks `gh` which STEP failed, then looks that step's NAME up in this
// workflow's own `working-directory:` keys to answer *"which package was
// it testing, and does this push change anything under it"*. The map is
// READ out of the repository rather than typed into the hook — NEVER
// TYPE A PATH YOU CAN DERIVE (docs/CONVENTIONS.md) — and that derivation
// is what creates the dependency this section keeps.
//
// EVERY BODY ABOVE PINS A COMMAND AND NONE OF THEM PINS A NAME, which is
// the key the map is keyed on. `push-guard.spec.ts` pins four step names
// against the real file and nothing else; the general property belongs
// beside the workflow's other keepers rather than inside a hook's spec:
//
//   every step in every workflow file that declares a `working-directory`
//   names a directory that is in this tree, and the guard's own scanner
//   reads exactly the value the YAML parser reads — for the steps that
//   declare none as much as for the steps that do, because the guard
//   says a DIFFERENT sentence for those ("runs at the repository root
//   and EVERY push reaches it").
//
// The scanner is IMPORTED, never re-implemented. A second copy of its
// line regex here would agree with itself while drifting from the hook,
// which is the mirror failure T-045 already took out of this file once.

/** A workflow file and its bytes — the pair every check below needs. */
interface WorkflowFile {
  /** repo-relative, POSIX-spelled, so a complaint names a path a reader can open */
  rel: string;
  raw: string;
}

/** One step of one workflow file, as the YAML parser sees it. */
interface StepSite {
  file: string;
  job: string;
  /** position in that job's `steps:` list, so an UNNAMED step still has a site */
  index: number;
  name: string | undefined;
  /** the YAML parser's own `working-directory`, undefined when the step declares none */
  dir: string | undefined;
}

/**
 * EVERY workflow file in the tree, not only the one the guard names.
 *
 * THROWS on an empty enumeration, and `readdirSync` throws on a missing
 * directory — the same red by a different message. This section exists
 * because a reader of these files went unnoticed, so a census that found
 * nothing must be a hard failure rather than a loop that passes by
 * having nothing to iterate (docs/CONVENTIONS.md, A NEGATIVE ASSERTION
 * NEEDS A POSITIVE CONTROL, and its census clause).
 */
export function workflowFiles(): WorkflowFile[] {
  const dir = path.join(repoRoot, ".github", "workflows");
  const names = readdirSync(dir)
    .filter((f) => /\.ya?ml$/.test(f))
    .sort();
  if (names.length === 0) {
    throw new Error(
      `${dir} holds no workflow file — push-guard.mjs reads one at push time ` +
        "(T-237) and this section is that dependency's keeper, so an empty " +
        "enumeration is a failure and never a vacuous pass.",
    );
  }
  return names.map((f) => ({
    rel: path.posix.join(".github", "workflows", f),
    raw: readFileSync(path.join(dir, f), "utf8"),
  }));
}

/** Every step of every job, in file order. */
export function stepSites(files: WorkflowFile[]): StepSite[] {
  const sites: StepSite[] = [];
  for (const { rel, raw } of files) {
    const doc = parse(raw) as { jobs?: Record<string, { steps?: WorkflowStep[] }> };
    for (const [job, body] of Object.entries(doc.jobs ?? {})) {
      (body.steps ?? []).forEach((step, index) => {
        sites.push({ file: rel, job, index, name: step.name, dir: step["working-directory"] });
      });
    }
  }
  return sites;
}

const siteLabel = (s: StepSite): string =>
  `${s.file} job \`${s.job}\` step ${String(s.index)} ` +
  (s.name === undefined ? "(UNNAMED)" : `\`${s.name}\``);

/**
 * Where the guard's step->package map disagrees with the workflow, or
 * names a package that is not here. `problems` empty is the assertion;
 * each entry names the step it is about and what to do, the way
 * `deriveExpectedSteps` does for the command list.
 *
 * Takes its files as ARGUMENTS so a fixture can feed it a synthetic
 * workflow — no body here writes to `.github/`, and the real ci.yml is
 * never renamed by this suite.
 */
export function stepPackageProblems(files: WorkflowFile[]): {
  sites: StepSite[];
  problems: string[];
} {
  const sites = stepSites(files);
  const bytes = new Map(files.map((f) => [f.rel, f.raw]));
  const problems: string[] = [];
  for (const site of sites) {
    const where = siteLabel(site);
    const text = bytes.get(site.file) ?? "";
    if (site.name === undefined) {
      if (site.dir !== undefined) {
        problems.push(
          `${where} declares \`working-directory: ${site.dir}\` but the item has no ` +
            "`name:`. `gh` reports a failing step BY NAME and push-guard.mjs looks " +
            "that name up in this file, so an unnamed step is unplaceable by " +
            "construction and its package can never reach the seat. Name it.",
        );
      }
      continue;
    }
    const read = stepWorkingDirectory(text, site.name);
    if (read !== site.dir) {
      problems.push(
        `${where}: the workflow says ` +
          (site.dir === undefined
            ? "this step has NO `working-directory`"
            : `\`working-directory: ${site.dir}\``) +
          ", and push-guard.mjs's own stepWorkingDirectory reads " +
          (read === undefined ? "NOTHING" : `\`${read}\``) +
          " for that name. The guard's step->package map is READ out of this file " +
          "(T-237), and the one shape that scanner claims is a sequence item whose " +
          "FIRST key is `name:` with `working-directory:` indented under it. A step " +
          "the scanner cannot place is NOT announced as unplaceable: the guard reads " +
          "`undefined` for it, which is also what a root-running step reads as, and " +
          "announces the step as running at the repository root where EVERY push " +
          "reaches it.",
      );
    }
    if (site.dir !== undefined && !existsSync(path.join(repoRoot, site.dir))) {
      problems.push(
        `${where} names \`working-directory: ${site.dir}\`, which is not in this tree. ` +
          "push-guard.mjs prints that path at the seat when CI is red and tests the " +
          'pushed paths against it, so a package that is not there answers "does NOT ' +
          'change anything under it" for every push.',
      );
    }
  }
  return { sites, problems };
}

test("every workflow step's package is readable by the push guard and is in the tree", () => {
  const files = workflowFiles();

  // The file the guard actually opens is one of these, and it is HERE.
  // A `CI_WORKFLOW_REL_PATH` that stops naming a file reds this body
  // rather than skipping it — the hook's own catch turns that case into
  // a lost sentence at the seat, which is exactly the silence this
  // section exists to break.
  expect(
    files.map((f) => f.rel),
    `push-guard.mjs reads ${CI_WORKFLOW_REL_PATH} at push time; the enumeration must cover it`,
  ).toContain(CI_WORKFLOW_REL_PATH);
  expect(
    existsSync(path.join(repoRoot, CI_WORKFLOW_REL_PATH)),
    `${CI_WORKFLOW_REL_PATH} is the path push-guard.mjs opens, and it is not in this tree`,
  ).toBe(true);

  const { sites, problems } = stepPackageProblems(files);

  // THE CENSUS BEFORE ITS ZERO. A scanner that matched no steps would
  // satisfy the loop by finding nothing. FLOORS, not counts: ci.yml
  // gains steps, and an equality would make every such edit a two-file
  // change for no property — the argument the derived-step floor above
  // already makes.
  expect(sites.length, "enumerated workflow steps").toBeGreaterThan(0);
  expect(
    sites.filter((s) => s.dir !== undefined).length,
    "steps declaring a `working-directory` — the entries of the guard's map",
  ).toBeGreaterThan(0);
  // ...and the other category is non-empty too, so the guard's OTHER
  // sentence is exercised by a real step rather than assumed unreachable.
  expect(
    sites.some((s) => s.dir === undefined),
    "at least one step runs at the repository root",
  ).toBe(true);

  expect(
    problems,
    "these are the ways the workflow and the push guard's step->package map disagree",
  ).toEqual([]);
});

test("FIXTURE: renaming a step in a copy of ci.yml degrades the guard's lookup BY NAME", () => {
  const raw = readFileSync(path.join(repoRoot, CI_WORKFLOW_REL_PATH), "utf8");
  const victim = stepSites([{ rel: CI_WORKFLOW_REL_PATH, raw }]).find(
    (s) => s.name !== undefined && s.dir !== undefined,
  );
  expect(victim, "ci.yml has a named step carrying a `working-directory`").toBeDefined();
  const oldName = victim!.name!;
  const dir = victim!.dir!;

  // THE CONTROL'S OTHER HALF, and it is the same arrangement minus the
  // one edit: against the UNRENAMED copy the map is complete and the
  // guard answers with the package.
  expect(stepWorkingDirectory(raw, oldName), "the complete map answers with the package").toBe(dir);

  const marker = `name: ${oldName}`;
  expect(raw.split(marker).length - 1, "the step this fixture renames is written once").toBe(1);
  const newName = `${oldName} (renamed by this fixture)`;
  const renamed = raw.replace(marker, `name: ${newName}`);
  expect(renamed, "the fixture must actually change the workflow").not.toBe(raw);

  // THE DEGRADATION, BY NAME. Nothing was deleted — the KEY MOVED, and
  // every holder of the old name now gets `undefined`. That is the
  // production case rather than a hypothetical: `gh` reports the step
  // name from the run that ALREADY RAN, so the push that CARRIES a
  // rename is exactly the push whose announcement moves.
  expect(
    stepWorkingDirectory(renamed, oldName),
    `${oldName} no longer maps to ${dir} — the guard reads nothing for that name`,
  ).toBeUndefined();
  expect(stepWorkingDirectory(renamed, newName), "the key moved rather than vanished").toBe(dir);

  // AND WHAT IT MOVES TO, pinned at the guard's own input. `undefined`
  // is ALSO what a step that genuinely declares no `working-directory`
  // reads as, and the guard has no third value — so `reachSentence`
  // announces the renamed step as running at the repository root where
  // every push reaches it, which is a confident falsehood rather than
  // an admission. This body pins the collapse; the repair is the hook's
  // (T-237-s7) and cannot be made from inside this fence.
  const rootStep = stepSites([{ rel: CI_WORKFLOW_REL_PATH, raw }]).find(
    (s) => s.name !== undefined && s.dir === undefined,
  );
  expect(rootStep, "ci.yml has a step that genuinely runs at the repository root").toBeDefined();
  expect(
    stepWorkingDirectory(raw, rootStep!.name!),
    "a genuinely root-running step reads as nothing...",
  ).toBeUndefined();
  expect(
    stepWorkingDirectory(renamed, oldName),
    "...and the unplaceable step reads as the SAME value, so no sentence downstream can separate them",
  ).toBe(stepWorkingDirectory(raw, rootStep!.name!));

  // And a rename that moves BOTH sides at once is NOT a defect this
  // keeper reports: the parity above is scanner-against-YAML and both
  // read the new name. Asserted so this body cannot be read as banning
  // renames — what it pins is that the map stays READABLE.
  expect(
    stepPackageProblems([{ rel: CI_WORKFLOW_REL_PATH, raw: renamed }]).problems,
    "a rename keeps the workflow and the scanner in agreement",
  ).toEqual([]);
});

/**
 * A minimal workflow whose ONE step is spelled by the caller. The
 * control and each mutant differ in exactly the line under test, which
 * is what makes the pair a control rather than two arrangements decided
 * by one arming (method/roles/verifier.md step 2b).
 */
const fixtureWorkflow = (stepLines: string[]): WorkflowFile => ({
  rel: ".github/workflows/FIXTURE-never-written-to-disk.yml",
  raw: ["name: fixture", "jobs:", "  linux:", "    steps:"]
    .concat(stepLines.map((l) => `      ${l}`))
    .concat([""])
    .join("\n"),
});

const FIXTURE_STEP_NAME = "fixture step";

test("FIXTURE: an absent package, an unreadable step, an unnamed one and one read out of a run block each red BY NAME", () => {
  // THE CONTROL: the readable shape over a directory that really is
  // here derives clean, so every red below is the one edit and not the
  // scaffolding.
  const ok = fixtureWorkflow([
    `- name: ${FIXTURE_STEP_NAME}`,
    "  working-directory: tools/e2e",
    "  run: npm test",
  ]);
  expect(stepPackageProblems([ok]).problems, "the readable shape derives clean").toEqual([]);
  expect(stepWorkingDirectory(ok.raw, FIXTURE_STEP_NAME)).toBe("tools/e2e");

  // (1) a `working-directory` naming a directory that is NOT in the
  //     tree. Not a stub — `existsSync` is asked about the real repo,
  //     the same call the live body makes.
  const gone = fixtureWorkflow([
    `- name: ${FIXTURE_STEP_NAME}`,
    "  working-directory: tools/e2e-that-is-not-in-this-tree",
    "  run: npm test",
  ]);
  const goneSaid = stepPackageProblems([gone]).problems.join("\n");
  expect(goneSaid, "the step is named").toContain(FIXTURE_STEP_NAME);
  expect(goneSaid, "the package is named").toContain("tools/e2e-that-is-not-in-this-tree");
  expect(goneSaid).toContain("is not in this tree");

  // (2) a step the SCANNER cannot read: the same two keys, the other way
  //     round. The YAML parser answers `tools/e2e`; the guard's line
  //     scanner requires `name:` to be the item's FIRST key and answers
  //     nothing, so the map loses an entry with no other symptom — the
  //     silent shape this whole section is for.
  const unreadable = fixtureWorkflow([
    "- working-directory: tools/e2e",
    `  name: ${FIXTURE_STEP_NAME}`,
    "  run: npm test",
  ]);
  expect(
    stepWorkingDirectory(unreadable.raw, FIXTURE_STEP_NAME),
    "the scanner genuinely cannot read this shape — that is the premise",
  ).toBeUndefined();
  const unreadableSaid = stepPackageProblems([unreadable]).problems.join("\n");
  expect(unreadableSaid, "the step is named").toContain(FIXTURE_STEP_NAME);
  expect(unreadableSaid).toContain("reads NOTHING");
  //     ...and that NOTHING is the same value a genuinely root-running
  //     step reads as, which is why the guard announces the unplaceable
  //     step as running at the root instead of saying it cannot place
  //     it. The root-running step is not itself a defect — asserted, so
  //     this keeper cannot be read as banning one.
  const rooted = fixtureWorkflow([`- name: ${FIXTURE_STEP_NAME}`, "  run: npm test"]);
  expect(stepWorkingDirectory(rooted.raw, FIXTURE_STEP_NAME)).toBe(
    stepWorkingDirectory(unreadable.raw, FIXTURE_STEP_NAME),
  );
  expect(
    stepPackageProblems([rooted]).problems,
    "a step that genuinely runs at the repository root is not a defect",
  ).toEqual([]);

  // (4) THE OTHER DIRECTION, which no body above reaches: the scanner
  //     reads a `working-directory:` the YAML parser does NOT. Its line
  //     scan knows nothing about block scalars, so a `run: |` script
  //     that writes YAML hands it a package the step never declared —
  //     and the guard would then announce a package, and a reach
  //     verdict, for a step that actually runs at the root.
  const fromRunBlock = fixtureWorkflow([
    `- name: ${FIXTURE_STEP_NAME}`,
    "  run: |",
    "    cat > snippet.yml <<'YAML'",
    "    working-directory: tools/e2e",
    "    YAML",
  ]);
  expect(
    stepWorkingDirectory(fromRunBlock.raw, FIXTURE_STEP_NAME),
    "the scanner reads inside the block scalar — that is the premise",
  ).toBe("tools/e2e");
  const blockSaid = stepPackageProblems([fromRunBlock]).problems.join("\n");
  expect(blockSaid, "the step is named").toContain(FIXTURE_STEP_NAME);
  expect(blockSaid).toContain("has NO `working-directory`");
  expect(blockSaid).toContain("reads `tools/e2e`");

  // (3) a step carrying a package and no name at all. `gh` reports steps
  //     BY NAME, so this one is unplaceable however the scanner is
  //     written — a different repair from (2), hence a different
  //     sentence.
  const unnamed = fixtureWorkflow(["- working-directory: tools/e2e", "  run: npm test"]);
  const unnamedSaid = stepPackageProblems([unnamed]).problems.join("\n");
  expect(unnamedSaid, "the site is named even without a step name").toContain("(UNNAMED)");
  expect(unnamedSaid).toContain("has no `name:`");
});
