//! T-021: the webview ACL surface, PINNED (absorbs T-007-s2).
//!
//! ADR-012 keeps the webview grant set empty beyond `core:default`; the
//! T-007 verifier proved it once by hand. This module makes that proof a
//! permanent regression test built on the exact machinery that verdict
//! demonstrated:
//!
//! - the RESOLVED AUTHORITY is reconstructed from the SHIPPED artifacts —
//!   `gen/schemas/acl-manifests.json` (every registered ACL namespace)
//!   and `gen/schemas/capabilities.json` (the compiled capability set),
//!   both regenerated by tauri-build on every `cargo build`/`cargo test`
//!   of this crate — through `Resolved::resolve`, the same routine
//!   tauri-build itself runs;
//! - that authority is installed into a MockRuntime app (headless: no OS
//!   window, no event loop, no native dialog can appear) with the REAL
//!   `tauri_plugin_dialog::init()` registered and the REAL app commands
//!   in the invoke handler, and probed with real `InvokeRequest`s;
//! - the full grant set is pinned as `EXPECTED_GRANTS`. Any diff that
//!   moves the ACL surface — a new permission in a capability, a new
//!   capability file, a tauri upgrade that grows `core:default` — fails
//!   the pin WITH A DIFF of the grant set (the alarm F-04 depends on:
//!   the first webview-grant movement must be loud and enumerated, never
//!   silent).
//!
//! `strings` on a binary proves nothing about grants (capabilities
//! compile to code, not identifier strings — the T-007 verdict's
//! correction, recorded in CONVENTIONS); THIS file is the real evidence.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;
use std::sync::atomic::AtomicU64;
use std::sync::{mpsc, Arc};

use serde_json::json;
use tauri::ipc::{CallbackFn, InvokeBody, Origin};
use tauri::test::{get_ipc_response, mock_builder, mock_context, noop_assets, INVOKE_KEY};
use tauri::utils::acl::capability::Capability;
use tauri::utils::acl::manifest::Manifest;
use tauri::utils::acl::resolved::Resolved;
use tauri::utils::acl::ExecutionContext;
use tauri::utils::platform::Target;
use tauri::webview::InvokeRequest;

use crate::docs_watch::WatchState;

/// THE PINNED WEBVIEW GRANT SET — exactly what `core:default` resolves
/// to under this tree's shipped artifacts, and nothing else. One line
/// per resolved grant: `command @context windows=[...] webviews=[...]`,
/// sorted. If the test fails here, the webview ACL surface MOVED: read
/// the printed diff, and only re-pin if an ADR names the movement
/// deliberate (ADR-012 says the set stays empty beyond core:default
/// until F-04 changes it on purpose).
const EXPECTED_GRANTS: &[&str] = &[
    "plugin:app|bundle_type @local windows=[main] webviews=[]",
    "plugin:app|identifier @local windows=[main] webviews=[]",
    "plugin:app|name @local windows=[main] webviews=[]",
    "plugin:app|register_listener @local windows=[main] webviews=[]",
    "plugin:app|remove_listener @local windows=[main] webviews=[]",
    "plugin:app|supports_multiple_windows @local windows=[main] webviews=[]",
    "plugin:app|tauri_version @local windows=[main] webviews=[]",
    "plugin:app|version @local windows=[main] webviews=[]",
    "plugin:event|emit @local windows=[main] webviews=[]",
    "plugin:event|emit_to @local windows=[main] webviews=[]",
    "plugin:event|listen @local windows=[main] webviews=[]",
    "plugin:event|unlisten @local windows=[main] webviews=[]",
    "plugin:image|from_bytes @local windows=[main] webviews=[]",
    "plugin:image|from_path @local windows=[main] webviews=[]",
    "plugin:image|new @local windows=[main] webviews=[]",
    "plugin:image|rgba @local windows=[main] webviews=[]",
    "plugin:image|size @local windows=[main] webviews=[]",
    "plugin:menu|append @local windows=[main] webviews=[]",
    "plugin:menu|create_default @local windows=[main] webviews=[]",
    "plugin:menu|get @local windows=[main] webviews=[]",
    "plugin:menu|insert @local windows=[main] webviews=[]",
    "plugin:menu|is_checked @local windows=[main] webviews=[]",
    "plugin:menu|is_enabled @local windows=[main] webviews=[]",
    "plugin:menu|items @local windows=[main] webviews=[]",
    "plugin:menu|new @local windows=[main] webviews=[]",
    "plugin:menu|popup @local windows=[main] webviews=[]",
    "plugin:menu|prepend @local windows=[main] webviews=[]",
    "plugin:menu|remove @local windows=[main] webviews=[]",
    "plugin:menu|remove_at @local windows=[main] webviews=[]",
    "plugin:menu|set_accelerator @local windows=[main] webviews=[]",
    "plugin:menu|set_as_app_menu @local windows=[main] webviews=[]",
    "plugin:menu|set_as_help_menu_for_nsapp @local windows=[main] webviews=[]",
    "plugin:menu|set_as_window_menu @local windows=[main] webviews=[]",
    "plugin:menu|set_as_windows_menu_for_nsapp @local windows=[main] webviews=[]",
    "plugin:menu|set_checked @local windows=[main] webviews=[]",
    "plugin:menu|set_enabled @local windows=[main] webviews=[]",
    "plugin:menu|set_icon @local windows=[main] webviews=[]",
    "plugin:menu|set_text @local windows=[main] webviews=[]",
    "plugin:menu|text @local windows=[main] webviews=[]",
    "plugin:path|basename @local windows=[main] webviews=[]",
    "plugin:path|dirname @local windows=[main] webviews=[]",
    "plugin:path|extname @local windows=[main] webviews=[]",
    "plugin:path|is_absolute @local windows=[main] webviews=[]",
    "plugin:path|join @local windows=[main] webviews=[]",
    "plugin:path|normalize @local windows=[main] webviews=[]",
    "plugin:path|resolve @local windows=[main] webviews=[]",
    "plugin:path|resolve_directory @local windows=[main] webviews=[]",
    "plugin:resources|close @local windows=[main] webviews=[]",
    "plugin:tray|get_by_id @local windows=[main] webviews=[]",
    "plugin:tray|new @local windows=[main] webviews=[]",
    "plugin:tray|remove_by_id @local windows=[main] webviews=[]",
    "plugin:tray|set_icon @local windows=[main] webviews=[]",
    "plugin:tray|set_icon_as_template @local windows=[main] webviews=[]",
    "plugin:tray|set_icon_with_as_template @local windows=[main] webviews=[]",
    "plugin:tray|set_menu @local windows=[main] webviews=[]",
    "plugin:tray|set_show_menu_on_left_click @local windows=[main] webviews=[]",
    "plugin:tray|set_temp_dir_path @local windows=[main] webviews=[]",
    "plugin:tray|set_title @local windows=[main] webviews=[]",
    "plugin:tray|set_tooltip @local windows=[main] webviews=[]",
    "plugin:tray|set_visible @local windows=[main] webviews=[]",
    "plugin:webview|get_all_webviews @local windows=[main] webviews=[]",
    "plugin:webview|internal_toggle_devtools @local windows=[main] webviews=[]",
    "plugin:webview|webview_position @local windows=[main] webviews=[]",
    "plugin:webview|webview_size @local windows=[main] webviews=[]",
    "plugin:window|activity_name @local windows=[main] webviews=[]",
    "plugin:window|available_monitors @local windows=[main] webviews=[]",
    "plugin:window|current_monitor @local windows=[main] webviews=[]",
    "plugin:window|cursor_position @local windows=[main] webviews=[]",
    "plugin:window|get_all_windows @local windows=[main] webviews=[]",
    "plugin:window|inner_position @local windows=[main] webviews=[]",
    "plugin:window|inner_size @local windows=[main] webviews=[]",
    "plugin:window|internal_toggle_maximize @local windows=[main] webviews=[]",
    "plugin:window|is_always_on_top @local windows=[main] webviews=[]",
    "plugin:window|is_closable @local windows=[main] webviews=[]",
    "plugin:window|is_decorated @local windows=[main] webviews=[]",
    "plugin:window|is_enabled @local windows=[main] webviews=[]",
    "plugin:window|is_focused @local windows=[main] webviews=[]",
    "plugin:window|is_fullscreen @local windows=[main] webviews=[]",
    "plugin:window|is_maximizable @local windows=[main] webviews=[]",
    "plugin:window|is_maximized @local windows=[main] webviews=[]",
    "plugin:window|is_minimizable @local windows=[main] webviews=[]",
    "plugin:window|is_minimized @local windows=[main] webviews=[]",
    "plugin:window|is_resizable @local windows=[main] webviews=[]",
    "plugin:window|is_visible @local windows=[main] webviews=[]",
    "plugin:window|monitor_from_point @local windows=[main] webviews=[]",
    "plugin:window|outer_position @local windows=[main] webviews=[]",
    "plugin:window|outer_size @local windows=[main] webviews=[]",
    "plugin:window|primary_monitor @local windows=[main] webviews=[]",
    "plugin:window|scale_factor @local windows=[main] webviews=[]",
    "plugin:window|scene_identifier @local windows=[main] webviews=[]",
    "plugin:window|theme @local windows=[main] webviews=[]",
    "plugin:window|title @local windows=[main] webviews=[]",
];

fn manifest_dir() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

/// Every ACL namespace this build REGISTERED (core plugins + every
/// `.plugin(...)` init), as tauri-build compiled it.
fn shipped_manifests() -> BTreeMap<String, Manifest> {
    let path = manifest_dir().join("gen/schemas/acl-manifests.json");
    let raw = fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "{} unreadable ({err}) - tauri-build regenerates it on every cargo build/test",
            path.display()
        )
    });
    serde_json::from_str(&raw).expect("acl-manifests.json parses as BTreeMap<String, Manifest>")
}

/// The compiled capability set, as tauri-build resolved the
/// capabilities/ directory.
fn shipped_capabilities() -> BTreeMap<String, Capability> {
    let path = manifest_dir().join("gen/schemas/capabilities.json");
    let raw = fs::read_to_string(&path).unwrap_or_else(|err| {
        panic!(
            "{} unreadable ({err}) - tauri-build regenerates it on every cargo build/test",
            path.display()
        )
    });
    serde_json::from_str(&raw).expect("capabilities.json parses as BTreeMap<String, Capability>")
}

/// The resolved authority — `Resolved::resolve` is the exact routine
/// tauri-build runs to compile the runtime ACL.
fn resolve_shipped() -> Resolved {
    Resolved::resolve(&shipped_manifests(), shipped_capabilities(), Target::current())
        .expect("shipped ACL artifacts resolve")
}

/// One sorted, human-readable line per resolved grant. This rendering IS
/// the pinned surface: command, execution context, window/webview scope.
fn grant_lines(resolved: &Resolved) -> Vec<String> {
    let mut lines = Vec::new();
    for (cmd, entries) in &resolved.allowed_commands {
        for entry in entries {
            let context = match &entry.context {
                ExecutionContext::Local => "local".to_string(),
                ExecutionContext::Remote { url } => format!("remote:{}", url.as_str()),
            };
            let windows: Vec<_> = entry.windows.iter().map(|p| p.as_str()).collect();
            let webviews: Vec<_> = entry.webviews.iter().map(|p| p.as_str()).collect();
            lines.push(format!(
                "{cmd} @{context} windows=[{}] webviews=[{}]",
                windows.join(","),
                webviews.join(",")
            ));
        }
    }
    lines.sort();
    lines
}

fn bullet_block(lines: &[&String]) -> String {
    if lines.is_empty() {
        "  (none)".into()
    } else {
        lines
            .iter()
            .map(|l| format!("  {l}"))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Criterion 1+3: the zero-webview-surface proof as a pinned test. Any
/// future diff that moves the resolved grant set fails HERE, with a
/// diff of the grant set — the F-04 alarm.
#[test]
fn t021_webview_grant_set_is_pinned_and_diffs_on_movement() {
    let resolved = resolve_shipped();

    // Deny entries are surface movement too (they change how the ACL
    // decides); today there are none and the pin holds that.
    assert!(
        resolved.denied_commands.is_empty(),
        "denied_commands must stay empty; got: {:?}",
        resolved.denied_commands.keys().collect::<Vec<_>>()
    );
    // No scopes: nothing in core:default carries fs/asset scopes today.
    assert!(
        resolved.command_scope.is_empty() && resolved.global_scope.is_empty(),
        "scopes appeared in the resolved ACL - surface moved"
    );
    // No app ACL manifest: app commands stay un-gated locally and
    // remote-denied by capability absence (probed live below).
    assert!(
        !resolved.has_app_acl,
        "an app ACL manifest appeared - the app-command gating model changed"
    );

    let actual = grant_lines(&resolved);
    let expected: Vec<String> = EXPECTED_GRANTS.iter().map(|s| s.to_string()).collect();
    if actual != expected {
        let actual_set: BTreeSet<&String> = actual.iter().collect();
        let expected_set: BTreeSet<&String> = expected.iter().collect();
        let added: Vec<&String> = actual_set.difference(&expected_set).copied().collect();
        let removed: Vec<&String> = expected_set.difference(&actual_set).copied().collect();
        panic!(
            "\n\
             ================ WEBVIEW ACL SURFACE MOVED (T-021 pin) ================\n\
             The resolved webview grant set no longer matches the pinned surface.\n\
             This is the alarm F-04 depends on - do not silence it without an ADR.\n\
             \n\
             + granted now, not pinned:\n{}\n\
             - pinned, no longer granted:\n{}\n\
             \n\
             If this movement is INTENTIONAL and decided (ADR-012 supersession or\n\
             F-04 landing), re-pin EXPECTED_GRANTS in src/acl_pin.rs to the full\n\
             current set below; otherwise revert the capability/plugin change.\n\
             \n\
             Full current grant set ({} grants):\n{}\n\
             =======================================================================\n",
            bullet_block(&added),
            bullet_block(&removed),
            actual.len(),
            actual
                .iter()
                .map(|l| format!("  \"{l}\","))
                .collect::<Vec<_>>()
                .join("\n")
        );
    }
}

/// The capability SOURCE stays exactly as shipped: one file, one
/// capability, `core:default` only, main window, local-only. The
/// generated artifact must agree with the committed source — a stale or
/// bypassed tauri-build shows up here.
#[test]
fn t021_capability_source_is_exactly_core_default_local_main() {
    // Committed source: capabilities/ contains exactly default.json.
    let caps_dir = manifest_dir().join("capabilities");
    let mut files: Vec<String> = fs::read_dir(&caps_dir)
        .expect("capabilities/ exists")
        .map(|e| e.expect("dir entry").file_name().to_string_lossy().into_owned())
        .filter(|name| !name.starts_with('.'))
        .collect();
    files.sort();
    assert_eq!(
        files,
        vec!["default.json".to_string()],
        "capability FILES are part of the pinned surface - a new file is a new grant channel"
    );

    let source: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(caps_dir.join("default.json")).expect("read default.json"),
    )
    .expect("default.json parses");
    assert_eq!(source["identifier"], json!("default"));
    assert_eq!(source["windows"], json!(["main"]));
    assert_eq!(source["permissions"], json!(["core:default"]));
    assert!(
        source.get("remote").is_none(),
        "a remote key in the capability source grants remote origins - forbidden here"
    );
    assert!(
        source.get("local").map_or(true, |l| l == &json!(true)),
        "local defaults to true; pinning that no one flipped it meaningfully"
    );
    assert!(
        source.get("webviews").is_none(),
        "webview-targeted grants are new surface"
    );

    // Generated artifact: exactly one capability, agreeing with source.
    let built = shipped_capabilities();
    assert_eq!(
        built.keys().collect::<Vec<_>>(),
        vec!["default"],
        "the compiled capability set must contain exactly 'default'"
    );
    let cap = &built["default"];
    assert!(cap.local, "compiled capability must be local");
    assert!(cap.remote.is_none(), "compiled capability must have no remote origins");
    assert_eq!(cap.windows, vec!["main".to_string()]);
    assert!(cap.webviews.is_empty());
    assert_eq!(
        serde_json::to_value(&cap.permissions).expect("serialize permissions"),
        json!(["core:default"]),
        "compiled permissions must be exactly core:default"
    );

    // Registered namespaces: dialog IS registered (its denial below is a
    // real ACL decision, not absence); fs and opener are ABSENT (the
    // T-007 verdict shape - nothing to grant even by mistake).
    let manifests = shipped_manifests();
    assert!(
        manifests.contains_key("dialog"),
        "tauri-plugin-dialog registration must appear in the ACL manifests"
    );
    assert!(
        !manifests.contains_key("fs"),
        "the fs plugin must never be initialized (type-only transitive, T-007)"
    );
    assert!(
        !manifests.contains_key("opener"),
        "no opener plugin may be registered"
    );
}

fn invoke_request(cmd: &str, url: &str, body: InvokeBody) -> InvokeRequest {
    InvokeRequest {
        cmd: cmd.into(),
        callback: CallbackFn(0),
        error: CallbackFn(1),
        url: url.parse().expect("probe url parses"),
        body,
        headers: Default::default(),
        invoke_key: INVOKE_KEY.to_string(),
    }
}

/// The local origin as the webview sees it (macOS/Linux serve
/// tauri://localhost; Windows/Android serve https://tauri.localhost).
fn local_origin() -> &'static str {
    if cfg!(any(windows, target_os = "android")) {
        "https://tauri.localhost"
    } else {
        "tauri://localhost"
    }
}

const REMOTE_ORIGIN: &str = "https://evil.example.com";

/// Criterion 1, the runtime half: REAL InvokeRequests against a
/// MockRuntime app carrying the RESOLVED AUTHORITY FROM THE SHIPPED
/// ARTIFACTS, the real dialog plugin, and the real app commands.
/// Headless by construction: MockRuntime creates no OS window, and every
/// dialog/fs/opener invoke is rejected by the ACL before any plugin code
/// (let alone a native dialog) could run.
#[test]
fn t021_real_invokes_dialog_fs_opener_denied_app_allowed_remote_denied() {
    // The authority under test is the SHIPPED one, not a fixture.
    let mut context = mock_context(noop_assets());
    *context.runtime_authority_mut() =
        tauri::runtime_authority!(shipped_manifests(), resolve_shipped());

    // Managed WatchState with a detached control channel: docs_snapshot
    // answers NoProject without any watcher thread.
    let (ctl, _ctl_rx) = mpsc::channel();
    let state = WatchState::new(None, Arc::new(AtomicU64::new(0)), ctl);

    // Handler: the REAL docs_snapshot (State-based, runtime-generic).
    // pick_project_folder and index_repo take `tauri::AppHandle` — the
    // Wry-monomorphic alias — so they cannot register on MockRuntime;
    // their ACL treatment is identical by construction (the reject/pass
    // decision runs on the command NAME before any handler lookup, and
    // `has_app_acl == false` gates ALL app commands the same way — both
    // pinned in the grant-set test), and their remote-origin denials are
    // probed below, where rejection provably precedes dispatch.
    let app = mock_builder()
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![crate::docs_snapshot])
        .manage(state)
        .build(context)
        .expect("mock app builds with the shipped authority");
    let webview = tauri::WebviewWindowBuilder::new(&app, "main", Default::default())
        .build()
        .expect("mock 'main' webview window (the capability's window label)");

    let deny = |cmd: &str| {
        let err = get_ipc_response(&webview, invoke_request(cmd, local_origin(), InvokeBody::default()))
            .expect_err(&format!("{cmd} must be DENIED from the local origin"));
        let msg = err.as_str().map(str::to_string).unwrap_or_else(|| err.to_string());
        assert!(
            msg.contains("not allowed"),
            "{cmd} denial must be an ACL decision, got: {msg}"
        );
        msg
    };

    // Dialog: registered namespace, zero grants. The plugin's REAL
    // command surface is open/save/message (the ask/confirm/message JS
    // APIs all invoke the `message` command - visible in the manifest,
    // where allow-ask/allow-confirm/allow-message all allow `message`).
    // Denied as a REAL ACL decision naming the missing permissions.
    for cmd in ["plugin:dialog|open", "plugin:dialog|save", "plugin:dialog|message"] {
        let _msg = deny(cmd);
        // Debug builds explain WHY: the associated dialog permission
        // exists and is simply not granted (denial-not-absence).
        #[cfg(debug_assertions)]
        assert!(
            _msg.contains("dialog:"),
            "{cmd}: expected the dialog permissions named, got: {_msg}"
        );
    }
    // Names an attacker might try that the manifest does not declare as
    // commands: denied too (unknown command under a registered
    // namespace), for the same "not allowed" wall.
    for cmd in ["plugin:dialog|ask", "plugin:dialog|confirm"] {
        let _msg = deny(cmd);
        #[cfg(debug_assertions)]
        assert!(
            _msg.contains("Command not found"),
            "{cmd} is not a declared dialog command; got: {_msg}"
        );
    }

    // fs: namespace never registered -> unreachable.
    for cmd in [
        "plugin:fs|read_file",
        "plugin:fs|read_text_file",
        "plugin:fs|write_file",
        "plugin:fs|write_text_file",
        "plugin:fs|remove",
        "plugin:fs|mkdir",
        "plugin:fs|copy_file",
        "plugin:fs|rename",
    ] {
        let _msg = deny(cmd);
        #[cfg(debug_assertions)]
        assert!(
            _msg.contains("Plugin not found"),
            "{cmd}: fs must not even be registered, got: {_msg}"
        );
    }

    // opener: never registered (T-001 regression shape).
    for cmd in [
        "plugin:opener|open_url",
        "plugin:opener|open_path",
        "plugin:opener|reveal_item_in_dir",
    ] {
        let _msg = deny(cmd);
        #[cfg(debug_assertions)]
        assert!(
            _msg.contains("Plugin not found"),
            "{cmd}: opener must not even be registered, got: {_msg}"
        );
    }

    // Positive controls - the denials above are decisions, not wreckage:
    // (a) the app's own command EXECUTES from the local origin, through
    // the real handler and the real managed state, and answers its real
    // typed payload. (pick_project_folder is deliberately NEVER invoked
    // from the local origin in any test - reaching its handler would ask
    // the dialog plugin for a native dialog; headless rule.)
    let status = get_ipc_response(
        &webview,
        invoke_request("docs_snapshot", local_origin(), InvokeBody::default()),
    )
    .expect("docs_snapshot must be allowed from the local origin")
    .deserialize::<serde_json::Value>()
    .expect("docs_snapshot answers JSON");
    assert_eq!(status, json!({ "kind": "noProject" }));

    // (b) a core:default plugin command passes the ACL gate (any failure
    // is at worst an argument error, never a denial).
    let listen = get_ipc_response(
        &webview,
        invoke_request(
            "plugin:event|listen",
            local_origin(),
            InvokeBody::Json(json!({
                "event": "t021-acl-probe",
                "target": { "kind": "Any" },
                "handler": 0
            })),
        ),
    );
    if let Err(err) = listen {
        let msg = err.as_str().map(str::to_string).unwrap_or_else(|| err.to_string());
        assert!(
            !msg.contains("not allowed"),
            "plugin:event|listen is core:default and must pass the ACL, got: {msg}"
        );
    }

    // Remote origins: the capability is local-only, so EVERYTHING is
    // denied - the app's own commands included (T-007 verdict's bonus
    // finding, now pinned).
    for cmd in [
        "docs_snapshot",
        "pick_project_folder",
        "index_repo",
        "plugin:event|listen",
        "plugin:dialog|open",
    ] {
        let err = get_ipc_response(&webview, invoke_request(cmd, REMOTE_ORIGIN, InvokeBody::default()))
            .expect_err(&format!("{cmd} must be DENIED from a remote origin"));
        let msg = err.as_str().map(str::to_string).unwrap_or_else(|| err.to_string());
        assert!(
            msg.contains("not allowed"),
            "{cmd} remote denial must be an ACL decision, got: {msg}"
        );
    }
}

/// The authority-level cross-check (the T-007 verifier's fourth layer):
/// no dialog/fs/opener command resolves under the shipped grant set —
/// enumerated from the dialog plugin's OWN manifest so new dialog
/// commands are auto-probed — while core:default's commands do resolve,
/// and nothing resolves for remote origins.
#[test]
fn t021_authority_resolves_no_dialog_fs_opener_command_but_core_default_yes() {
    let manifests = shipped_manifests();
    let authority = tauri::runtime_authority!(shipped_manifests(), resolve_shipped());
    let local = Origin::Local;
    let remote = Origin::Remote {
        url: REMOTE_ORIGIN.parse().expect("remote url"),
    };

    // Every command the dialog manifest itself declares (default perm +
    // every named permission), probed as unreachable.
    let dialog = manifests
        .get("dialog")
        .expect("dialog namespace registered");
    let mut dialog_commands: BTreeSet<&str> = BTreeSet::new();
    for permission in dialog.permissions.values() {
        for cmd in &permission.commands.allow {
            dialog_commands.insert(cmd);
        }
    }
    assert!(
        !dialog_commands.is_empty(),
        "the dialog manifest must declare commands (else this probe is vacuous)"
    );
    for cmd in dialog_commands {
        assert!(
            authority
                .resolve_access(&format!("plugin:dialog|{cmd}"), "main", "main", &local)
                .is_none(),
            "plugin:dialog|{cmd} must not resolve under the shipped grant set"
        );
    }
    for cmd in ["read_file", "read_text_file", "write_file", "remove"] {
        assert!(
            authority
                .resolve_access(&format!("plugin:fs|{cmd}"), "main", "main", &local)
                .is_none(),
            "plugin:fs|{cmd} must not resolve"
        );
    }
    for cmd in ["open_url", "open_path"] {
        assert!(
            authority
                .resolve_access(&format!("plugin:opener|{cmd}"), "main", "main", &local)
                .is_none(),
            "plugin:opener|{cmd} must not resolve"
        );
    }

    // core:default resolves for the main window from the local origin...
    assert!(
        authority
            .resolve_access("plugin:event|listen", "main", "main", &local)
            .is_some(),
        "plugin:event|listen (core:default) must resolve for main/local"
    );
    // ...but not for a window outside the capability...
    assert!(
        authority
            .resolve_access("plugin:event|listen", "other", "other", &local)
            .is_none(),
        "the capability is scoped to the main window"
    );
    // ...and never for remote origins.
    assert!(
        authority
            .resolve_access("plugin:event|listen", "main", "main", &remote)
            .is_none(),
        "nothing may resolve for remote origins"
    );
}

/// Determinism guard for the pin itself: resolving the same shipped
/// artifacts twice yields the same rendered grant set (BTreeMap-ordered,
/// no set-iteration or hash luck in the pinned rendering).
#[test]
fn t021_grant_set_rendering_is_deterministic() {
    assert_eq!(grant_lines(&resolve_shipped()), grant_lines(&resolve_shipped()));
}
